import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const root = resolve(process.cwd());
const source = JSON.parse(await readFile(resolve(root, "contracts/openapi/openapi.json"), "utf8"));
const readSchema = async (name) =>
  JSON.parse(await readFile(resolve(root, `contracts/schemas/${name}.schema.json`), "utf8"));
const [jobSchema, resultSchema, manifestSchema, versionErrorSchema] = await Promise.all([
  readSchema("job-envelope"),
  readSchema("result-envelope"),
  readSchema("import-manifest"),
  readSchema("version-error"),
]);
const schemaVersion = jobSchema.properties.schema_version.const;
if (
  resultSchema.properties.schema_version.const !== schemaVersion ||
  manifestSchema.properties.schema_version.const !== schemaVersion ||
  versionErrorSchema.properties.code.const !== "ATLAS_UNKNOWN_SCHEMA_VERSION"
) {
  throw new Error("contract schema versions or stable error code are inconsistent");
}
const assertSchemaShape = (schema, name, properties, required) => {
  const actualProperties = Object.keys(schema.properties ?? {});
  const actualRequired = schema.required ?? [];
  if (
    JSON.stringify(actualProperties) !== JSON.stringify(properties) ||
    JSON.stringify(actualRequired) !== JSON.stringify(required)
  ) {
    throw new Error(`${name} schema changed without updating the generator template`);
  }
};
assertSchemaShape(
  jobSchema,
  "job-envelope",
  ["kind", "schema_version", "idempotency_key", "input_snapshot_ids", "payload"],
  ["kind", "schema_version", "idempotency_key", "input_snapshot_ids", "payload"],
);
assertSchemaShape(
  resultSchema,
  "result-envelope",
  [
    "job_id",
    "schema_version",
    "status",
    "input_snapshot_ids",
    "data_quality",
    "engine_version",
    "output",
  ],
  [
    "job_id",
    "schema_version",
    "status",
    "input_snapshot_ids",
    "data_quality",
    "engine_version",
    "output",
  ],
);
assertSchemaShape(
  manifestSchema,
  "import-manifest",
  ["schema_version", "source_name", "content_sha256", "object_key", "columns", "row_count"],
  ["schema_version", "source_name", "content_sha256", "object_key", "columns", "row_count"],
);
if (
  jobSchema.properties.input_snapshot_ids.uniqueItems !== true ||
  jobSchema.properties.input_snapshot_ids.items.minLength !== 1 ||
  resultSchema.properties.input_snapshot_ids.uniqueItems !== true ||
  resultSchema.properties.input_snapshot_ids.items.minLength !== 1 ||
  JSON.stringify(versionErrorSchema.properties.details.properties.supported_versions.const) !==
    JSON.stringify([schemaVersion])
) {
  throw new Error("generator template does not preserve schema collection constraints");
}
const header = "// Code generated by scripts/generate/contract-models.mjs; DO NOT EDIT.\n";
const pythonHeader = "# Code generated by scripts/generate/contract-models.mjs; DO NOT EDIT.\n";

const write = async (relativePath, contents) => {
  const target = resolve(root, relativePath);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, contents, "utf8");
};

const go = `${header}// AtlasRisk contract models for ${source.info.title}.
package contracts

import "encoding/json"

const SupportedSchemaVersion = "${schemaVersion}"
const UnknownSchemaVersionCode = "ATLAS_UNKNOWN_SCHEMA_VERSION"

type ErrorEnvelope struct {
\tCode      string         \`json:"code"\`
\tMessage   string         \`json:"message"\`
\tRequestID string         \`json:"request_id"\`
\tDetails   map[string]any \`json:"details,omitempty"\`
}

type PageMeta struct {
\tLimit      int    \`json:"limit"\`
\tNextCursor string \`json:"next_cursor,omitempty"\`
\tHasMore    bool   \`json:"has_more"\`
}

type JobEnvelope struct {
\tKind             string          \`json:"kind"\`
\tSchemaVersion    string          \`json:"schema_version"\`
\tIdempotencyKey   string          \`json:"idempotency_key"\`
\tInputSnapshotIDs []string        \`json:"input_snapshot_ids"\`
\tPayload          json.RawMessage \`json:"payload"\`
}

type ResultEnvelope struct {
\tJobID            string          \`json:"job_id"\`
\tSchemaVersion    string          \`json:"schema_version"\`
\tStatus           string          \`json:"status"\`
\tInputSnapshotIDs []string        \`json:"input_snapshot_ids"\`
\tDataQuality      string          \`json:"data_quality"\`
\tEngineVersion    string          \`json:"engine_version"\`
\tOutput           json.RawMessage \`json:"output"\`
}

type ImportColumn struct {
\tName     string \`json:"name"\`
\tDataType string \`json:"data_type"\`
}

type ImportManifest struct {
\tSchemaVersion string         \`json:"schema_version"\`
\tSourceName    string         \`json:"source_name"\`
\tContentSHA256 string         \`json:"content_sha256"\`
\tObjectKey     string         \`json:"object_key"\`
\tColumns       []ImportColumn \`json:"columns"\`
\tRowCount      int            \`json:"row_count"\`
}

type UnknownSchemaVersionDetails struct {
\tKind              string   \`json:"kind"\`
\tSchemaVersion     string   \`json:"schema_version"\`
\tSupportedVersions []string \`json:"supported_versions"\`
}
`;

const typescript = `${header}export const SUPPORTED_SCHEMA_VERSION = "${schemaVersion}" as const;
export const UNKNOWN_SCHEMA_VERSION_CODE = "ATLAS_UNKNOWN_SCHEMA_VERSION" as const;

export interface ErrorEnvelope {
  code: string;
  message: string;
  request_id: string;
  details?: Record<string, unknown>;
}

export interface PageMeta {
  limit: number;
  next_cursor?: string;
  has_more: boolean;
}

export interface JobEnvelope {
  kind: string;
  schema_version: string;
  idempotency_key: string;
  input_snapshot_ids: string[];
  payload: Record<string, unknown>;
}

export type ResultStatus = "succeeded" | "degraded" | "blocked" | "failed";
export type DataQuality = "healthy" | "degraded" | "blocked";

export interface ResultEnvelope {
  job_id: string;
  schema_version: string;
  status: ResultStatus;
  input_snapshot_ids: string[];
  data_quality: DataQuality;
  engine_version: string;
  output: Record<string, unknown>;
}

export type ImportColumnType = "string" | "decimal" | "date" | "datetime";
export interface ImportColumn { name: string; data_type: ImportColumnType; }
export interface ImportManifest {
  schema_version: string;
  source_name: string;
  content_sha256: string;
  object_key: string;
  columns: ImportColumn[];
  row_count: number;
}

export interface UnknownSchemaVersionDetails {
  kind: string;
  schema_version: string;
  supported_versions: string[];
}
`;

const python = `${pythonHeader}from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

SUPPORTED_SCHEMA_VERSION = "${schemaVersion}"
UNKNOWN_SCHEMA_VERSION_CODE = "ATLAS_UNKNOWN_SCHEMA_VERSION"


class ContractModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class ErrorEnvelope(ContractModel):
    code: str = Field(pattern=r"^[A-Z][A-Z0-9_.-]+$")
    message: str = Field(min_length=1)
    request_id: str = Field(min_length=1, max_length=128)
    details: dict[str, Any] | None = None


class PageMeta(ContractModel):
    limit: int = Field(ge=1, le=200)
    next_cursor: str | None = Field(default=None, min_length=1)
    has_more: bool


class JobEnvelope(ContractModel):
    kind: str = Field(pattern=r"^[a-z][a-z0-9_.-]*$")
    schema_version: Literal["${schemaVersion}"]
    idempotency_key: str = Field(min_length=1, max_length=255)
    input_snapshot_ids: list[str] = Field(min_length=0)
    payload: dict[str, Any]

    @field_validator("input_snapshot_ids")
    @classmethod
    def snapshot_ids_are_unique(cls, value: list[str]) -> list[str]:
        if any(not snapshot_id for snapshot_id in value):
            raise ValueError("input_snapshot_ids entries must not be empty")
        if len(value) != len(set(value)):
            raise ValueError("input_snapshot_ids must contain unique values")
        return value


class ResultEnvelope(ContractModel):
    job_id: str = Field(min_length=1)
    schema_version: Literal["${schemaVersion}"]
    status: Literal["succeeded", "degraded", "blocked", "failed"]
    input_snapshot_ids: list[str] = Field(min_length=0)
    data_quality: Literal["healthy", "degraded", "blocked"]
    engine_version: str = Field(min_length=1)
    output: dict[str, Any]

    @field_validator("input_snapshot_ids")
    @classmethod
    def snapshot_ids_are_unique(cls, value: list[str]) -> list[str]:
        if any(not snapshot_id for snapshot_id in value):
            raise ValueError("input_snapshot_ids entries must not be empty")
        if len(value) != len(set(value)):
            raise ValueError("input_snapshot_ids must contain unique values")
        return value


class ImportColumn(ContractModel):
    name: str = Field(min_length=1)
    data_type: Literal["string", "decimal", "date", "datetime"]


class ImportManifest(ContractModel):
    schema_version: Literal["${schemaVersion}"]
    source_name: str = Field(min_length=1)
    content_sha256: str = Field(pattern=r"^[a-f0-9]{64}$")
    object_key: str = Field(min_length=1)
    columns: list[ImportColumn] = Field(min_length=1)
    row_count: int = Field(ge=0)


class UnknownSchemaVersionDetails(ContractModel):
    kind: str = Field(min_length=1)
    schema_version: str = Field(min_length=1)
    supported_versions: list[Literal["${schemaVersion}"]] = Field(
        min_length=1, max_length=1
    )
`;

await write("contracts/generated/go/contracts.go", go);
await write("contracts/generated/typescript/contracts.ts", typescript);
await write("contracts/generated/python/contracts.py", python);
await write(
  "contracts/generated/python/__init__.py",
  `${pythonHeader}from .contracts import (\n    ErrorEnvelope,\n    ImportColumn,\n    ImportManifest,\n    JobEnvelope,\n    PageMeta,\n    ResultEnvelope,\n    UnknownSchemaVersionDetails,\n)\n\n__all__ = [\n    "ErrorEnvelope",\n    "ImportColumn",\n    "ImportManifest",\n    "JobEnvelope",\n    "PageMeta",\n    "ResultEnvelope",\n    "UnknownSchemaVersionDetails",\n]\n`,
);
console.log("Generated Go, TypeScript, and Python contract models.");
