import { mkdir, readFile, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { dirname, resolve } from "node:path";
import { promisify } from "node:util";

const root = resolve(process.cwd());
const run = promisify(execFile);
const source = JSON.parse(await readFile(resolve(root, "contracts/openapi/openapi.json"), "utf8"));
const readSchema = async (name) =>
  JSON.parse(await readFile(resolve(root, `contracts/schemas/${name}.schema.json`), "utf8"));
const [errorSchema, jobSchema, resultSchema, manifestSchema, versionErrorSchema] = await Promise.all([
  readSchema("error-envelope"),
  readSchema("job-envelope"),
  readSchema("result-envelope"),
  readSchema("import-manifest"),
  readSchema("version-error"),
]);
const schemaVersion = jobSchema.properties.schema_version.const;
if (
  resultSchema.properties.schema_version.const !== schemaVersion ||
  manifestSchema.properties.schema_version.const !== schemaVersion ||
  versionErrorSchema.properties.code.const !== "ATLAS_UNKNOWN_SCHEMA_VERSION"
) {
  throw new Error("contract schema versions or stable error code are inconsistent");
}
const header = "// Code generated by scripts/generate/contract-models.mjs; DO NOT EDIT.\n";
const pythonHeader = "# Code generated by scripts/generate/contract-models.mjs; DO NOT EDIT.\n";

const pascal = (name) =>
  name
    .split("_")
    .map((part) => ({ id: "ID", ids: "IDs", sha256: "SHA256" })[part] ?? part[0].toUpperCase() + part.slice(1))
    .join("");
const goNamedTypes = new Map();
const goValueIdentifier = (value) => {
  const normalized = String(value).replace(/[^A-Za-z0-9]+/g, "_");
  const identifier = normalized.replace(/^([^A-Za-z_])/, "V$1");
  return identifier[0].toUpperCase() + identifier.slice(1);
};
const goNamedType = (name, property) => {
  const values = property.enum ?? (property.const !== undefined ? [property.const] : []);
  const existing = goNamedTypes.get(name);
  if (existing && JSON.stringify(existing) !== JSON.stringify(values)) {
    throw new Error(`conflicting generated Go type ${name}`);
  }
  goNamedTypes.set(name, values);
  return name;
};
const goType = (property, nestedName, fieldTypeName) => {
  if (property.type === "array") {
    if (property.items?.type === "object") return `[]${nestedName}`;
    const item = property.items ?? (Array.isArray(property.const) ? { type: "string", enum: property.const } : {});
    if (item.const !== undefined || item.enum) {
      return `[]${goNamedType(`${fieldTypeName}Item`, item)}`;
    }
    return "[]string";
  }
  if (property.const !== undefined || property.enum) return goNamedType(fieldTypeName, property);
  if (property.type === "string") return "string";
  if (property.type === "integer") return "int";
  if (property.type === "number") return "float64";
  if (property.type === "boolean") return "bool";
  return "map[string]any";
};
const tsType = (property, nestedName) => {
  if (property.type === "array") {
    if (property.items?.type === "object") return `${nestedName}[]`;
    if (Array.isArray(property.const)) return `[${property.const.map((value) => JSON.stringify(value)).join(", ")}]`;
    return "string[]";
  }
  if (property.const !== undefined) return JSON.stringify(property.const);
  if (property.enum) return property.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (property.type === "string") return "string";
  if (property.type === "integer" || property.type === "number") return "number";
  if (property.type === "boolean") return "boolean";
  return "Record<string, unknown>";
};
const pyType = (property, nestedName) => {
  if (property.type === "array") {
    if (property.items?.type === "object") return `list[${nestedName}]`;
    if (property.items?.minLength) {
      return `list[Annotated[str, Field(min_length=${property.items.minLength})]]`;
    }
    if (property.items?.const !== undefined) {
      return `list[Literal[${JSON.stringify(property.items.const)}]]`;
    }
    if (Array.isArray(property.const)) return `list[Literal[${JSON.stringify(property.const[0])}]]`;
    return "list[str]";
  }
  if (property.const !== undefined) return `Literal[${JSON.stringify(property.const)}]`;
  if (property.enum) return `Literal[${property.enum.map((value) => JSON.stringify(value)).join(", ")}]`;
  if (property.type === "string") return "str";
  if (property.type === "integer") return "int";
  if (property.type === "number") return "float";
  if (property.type === "boolean") return "bool";
  return "dict[str, Any]";
};
const goFields = (schema, nestedName, modelName) =>
  Object.entries(schema.properties).map(([name, property]) => {
    const optional = !(schema.required ?? []).includes(name);
    const tag = `json:"${name}${optional ? ",omitempty" : ""}"`;
    return `\t${pascal(name)} ${goType(property, nestedName, `${modelName}${pascal(name)}`)} \`${tag}\``;
  }).join("\n");
const tsFields = (schema, nestedName) =>
  Object.entries(schema.properties).map(([name, property]) => {
    const optional = !(schema.required ?? []).includes(name);
    return `  ${name}${optional ? "?" : ""}: ${tsType(property, nestedName)};`;
  }).join("\n");
const pyField = (name, property, required, nestedName) => {
  const type = pyType(property, nestedName);
  const constraints = [];
  for (const [schemaKey, fieldKey] of [["minLength", "min_length"], ["maxLength", "max_length"], ["pattern", "pattern"], ["minimum", "ge"], ["maximum", "le"], ["minItems", "min_length"], ["maxItems", "max_length"]]) {
    if (property[schemaKey] !== undefined) constraints.push(`${fieldKey}=${JSON.stringify(property[schemaKey])}`);
  }
  const suffix = required
    ? constraints.length > 0 ? ` = Field(${constraints.join(", ")})` : ""
    : ` = Field(default=None${constraints.length > 0 ? `, ${constraints.join(", ")}` : ""})`;
  return `    ${name}: ${required ? type : `${type} | None`}${suffix}`;
};
const pyFields = (schema, nestedName) =>
  Object.entries(schema.properties).map(([name, property]) =>
    pyField(name, property, (schema.required ?? []).includes(name), nestedName),
  ).join("\n");
const pyValidators = (schema) =>
  Object.entries(schema.properties).filter(([, property]) => property.uniqueItems).map(([name]) => `
    @field_validator("${name}")
    @classmethod
    def ${name}_are_unique(cls, value: list[str]) -> list[str]:
        if any(not item for item in value):
            raise ValueError("${name} entries must not be empty")
        if len(value) != len(set(value)):
            raise ValueError("${name} must contain unique values")
        return value
`).join("");

const write = async (relativePath, contents) => {
  const target = resolve(root, relativePath);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, contents, "utf8");
};

const goErrorFields = goFields(errorSchema, undefined, "ErrorEnvelope");
const goPageFields = goFields(source.components.schemas.PageMeta, undefined, "PageMeta");
const goJobFields = goFields(jobSchema, undefined, "JobEnvelope");
const goResultFields = goFields(resultSchema, undefined, "ResultEnvelope");
const goImportColumnFields = goFields(manifestSchema.properties.columns.items, undefined, "ImportColumn");
const goImportManifestFields = goFields(manifestSchema, "ImportColumn", "ImportManifest");
const goUnknownFields = goFields(versionErrorSchema.properties.details, undefined, "UnknownSchemaVersionDetails");
const goNamedDeclarations = [...goNamedTypes.entries()].map(([name, values]) => {
  const constants = values.map((value) => `\t${name}${goValueIdentifier(value)} ${name} = ${JSON.stringify(value)}`).join("\n");
  return `type ${name} string\n\nconst (\n${constants}\n)`;
}).join("\n\n");

const go = `${header}// AtlasRisk contract models for ${source.info.title}.
package contracts

const SupportedSchemaVersion = "${schemaVersion}"
const UnknownSchemaVersionCode = "ATLAS_UNKNOWN_SCHEMA_VERSION"

${goNamedDeclarations}

type ErrorEnvelope struct {
${goErrorFields}
}

type PageMeta struct {
${goPageFields}
}

type JobEnvelope struct {
${goJobFields}
}

type ResultEnvelope struct {
${goResultFields}
}

type ImportColumn struct {
${goImportColumnFields}
}

type ImportManifest struct {
${goImportManifestFields}
}

type UnknownSchemaVersionDetails struct {
${goUnknownFields}
}
`;

const typescript = `${header}export const SUPPORTED_SCHEMA_VERSION = "${schemaVersion}" as const;
export const UNKNOWN_SCHEMA_VERSION_CODE = "ATLAS_UNKNOWN_SCHEMA_VERSION" as const;

export interface ErrorEnvelope {
${tsFields(errorSchema)}
}

export interface PageMeta {
${tsFields(source.components.schemas.PageMeta)}
}

export interface JobEnvelope {
${tsFields(jobSchema)}
}

export type ResultStatus = ${tsType(resultSchema.properties.status)};
export type DataQuality = ${tsType(resultSchema.properties.data_quality)};

export interface ResultEnvelope {
${tsFields(resultSchema)}
}

export type ImportColumnType = ${tsType(manifestSchema.properties.columns.items.properties.data_type)};
export interface ImportColumn {
${tsFields(manifestSchema.properties.columns.items)}
}
export interface ImportManifest {
${tsFields(manifestSchema, "ImportColumn")}
}

export interface UnknownSchemaVersionDetails {
${tsFields(versionErrorSchema.properties.details)}
}
`;

const python = `${pythonHeader}from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

SUPPORTED_SCHEMA_VERSION = "${schemaVersion}"
UNKNOWN_SCHEMA_VERSION_CODE = "ATLAS_UNKNOWN_SCHEMA_VERSION"


class ContractModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class ErrorEnvelope(ContractModel):
${pyFields(errorSchema)}


class PageMeta(ContractModel):
${pyFields(source.components.schemas.PageMeta)}


class JobEnvelope(ContractModel):
${pyFields(jobSchema)}
${pyValidators(jobSchema)}


class ResultEnvelope(ContractModel):
${pyFields(resultSchema)}
${pyValidators(resultSchema)}


class ImportColumn(ContractModel):
${pyFields(manifestSchema.properties.columns.items)}


class ImportManifest(ContractModel):
${pyFields(manifestSchema, "ImportColumn")}


class UnknownSchemaVersionDetails(ContractModel):
${pyFields(versionErrorSchema.properties.details)}
`;

await write("contracts/generated/go/contracts.go", go);
await write("contracts/generated/typescript/contracts.ts", typescript);
await write("contracts/generated/python/contracts.py", python);
await write(
  "contracts/generated/python/__init__.py",
  `${pythonHeader}from .contracts import (\n    ErrorEnvelope,\n    ImportColumn,\n    ImportManifest,\n    JobEnvelope,\n    PageMeta,\n    ResultEnvelope,\n    UnknownSchemaVersionDetails,\n)\n\n__all__ = [\n    "ErrorEnvelope",\n    "ImportColumn",\n    "ImportManifest",\n    "JobEnvelope",\n    "PageMeta",\n    "ResultEnvelope",\n    "UnknownSchemaVersionDetails",\n]\n`,
);
await run("gofmt", ["-w", resolve(root, "contracts/generated/go/contracts.go")]);
console.log("Generated Go, TypeScript, and Python contract models.");
