import { mkdir, readFile, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { dirname, resolve } from "node:path";
import { promisify } from "node:util";

const root = resolve(process.cwd());
const run = promisify(execFile);
const source = JSON.parse(await readFile(resolve(root, "contracts/openapi/openapi.json"), "utf8"));
const readSchema = async (name) =>
  JSON.parse(await readFile(resolve(root, `contracts/schemas/${name}.schema.json`), "utf8"));
const [errorSchema, jobSchema, resultSchema, manifestSchema, versionErrorSchema] = await Promise.all([
  readSchema("error-envelope"),
  readSchema("job-envelope"),
  readSchema("result-envelope"),
  readSchema("import-manifest"),
  readSchema("version-error"),
]);
const schemaVersion = jobSchema.properties.schema_version.const;
if (
  resultSchema.properties.schema_version.const !== schemaVersion ||
  manifestSchema.properties.schema_version.const !== schemaVersion ||
  versionErrorSchema.properties.code.const !== "ATLAS_UNKNOWN_SCHEMA_VERSION"
) {
  throw new Error("contract schema versions or stable error code are inconsistent");
}
const header = "// Code generated by scripts/generate/contract-models.mjs; DO NOT EDIT.\n";
const pythonHeader = "# Code generated by scripts/generate/contract-models.mjs; DO NOT EDIT.\n";

const pascal = (name) =>
  name
    .split("_")
    .map((part) => ({ id: "ID", ids: "IDs", sha256: "SHA256" })[part] ?? part[0].toUpperCase() + part.slice(1))
    .join("");
const goNamedTypes = new Map();
const goValueIdentifier = (value) => {
  const normalized = String(value).replace(/[^A-Za-z0-9]+/g, "_");
  const identifier = normalized.replace(/^([^A-Za-z_])/, "V$1");
  return identifier[0].toUpperCase() + identifier.slice(1);
};
const goNamedType = (name, property) => {
  const values = property.enum ?? (property.const !== undefined ? [property.const] : []);
  const existing = goNamedTypes.get(name);
  if (existing && JSON.stringify(existing) !== JSON.stringify(values)) {
    throw new Error(`conflicting generated Go type ${name}`);
  }
  goNamedTypes.set(name, values);
  return name;
};
const goType = (property, nestedName, fieldTypeName) => {
  if (property.type === "array") {
    if (property.items?.type === "object") return `[]${nestedName}`;
    const item = property.items ?? (Array.isArray(property.const) ? { type: "string", enum: property.const } : {});
    if (item.const !== undefined || item.enum) {
      return `[]${goNamedType(`${fieldTypeName}Item`, item)}`;
    }
    return "[]string";
  }
  if (property.const !== undefined || property.enum) return goNamedType(fieldTypeName, property);
  if (property.type === "string") return "string";
  if (property.type === "integer") return "int";
  if (property.type === "number") return "float64";
  if (property.type === "boolean") return "bool";
  return "map[string]any";
};
const tsType = (property, nestedName) => {
  if (property.type === "array") {
    if (property.items?.type === "object") return `${nestedName}[]`;
    if (Array.isArray(property.const)) return `[${property.const.map((value) => JSON.stringify(value)).join(", ")}]`;
    return "string[]";
  }
  if (property.const !== undefined) return JSON.stringify(property.const);
  if (property.enum) return property.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (property.type === "string") return "string";
  if (property.type === "integer" || property.type === "number") return "number";
  if (property.type === "boolean") return "boolean";
  return "Record<string, unknown>";
};
const pyType = (property, nestedName) => {
  if (property.type === "array") {
    if (property.items?.type === "object") return `list[${nestedName}]`;
    if (property.items?.minLength) {
      return `list[Annotated[str, Field(min_length=${property.items.minLength})]]`;
    }
    if (property.items?.const !== undefined) {
      return `list[Literal[${JSON.stringify(property.items.const)}]]`;
    }
    if (Array.isArray(property.const)) return `list[Literal[${JSON.stringify(property.const[0])}]]`;
    return "list[str]";
  }
  if (property.const !== undefined) return `Literal[${JSON.stringify(property.const)}]`;
  if (property.enum) return `Literal[${property.enum.map((value) => JSON.stringify(value)).join(", ")}]`;
  if (property.type === "string") return "str";
  if (property.type === "integer") return "int";
  if (property.type === "number") return "float";
  if (property.type === "boolean") return "bool";
  return "dict[str, Any]";
};
const pyIdentifier = (name) => name === "try" ? "try_" : name;
const goFields = (schema, nestedName, modelName) =>
  Object.entries(schema.properties).map(([name, property]) => {
    const optional = !(schema.required ?? []).includes(name);
    const tag = `json:"${name}${optional ? ",omitempty" : ""}"`;
    return `\t${pascal(name)} ${goType(property, nestedName, `${modelName}${pascal(name)}`)} \`${tag}\``;
  }).join("\n");
const tsFields = (schema, nestedName) =>
  Object.entries(schema.properties).map(([name, property]) => {
    const optional = !(schema.required ?? []).includes(name);
    return `  ${name}${optional ? "?" : ""}: ${tsType(property, nestedName)};`;
  }).join("\n");
const pyField = (name, property, required, nestedName) => {
  const type = pyType(property, nestedName);
  const identifier = pyIdentifier(name);
  const constraints = [];
  for (const [schemaKey, fieldKey] of [["minLength", "min_length"], ["maxLength", "max_length"], ["pattern", "pattern"], ["minimum", "ge"], ["maximum", "le"], ["minItems", "min_length"], ["maxItems", "max_length"]]) {
    if (property[schemaKey] !== undefined) constraints.push(`${fieldKey}=${JSON.stringify(property[schemaKey])}`);
  }
  const suffix = required
    ? constraints.length > 0 ? ` = Field(${constraints.join(", ")})` : ""
    : ` = Field(default=None${constraints.length > 0 ? `, ${constraints.join(", ")}` : ""})`;
  const fieldArgs = [
    ...(identifier === name ? [] : [`alias=${JSON.stringify(name)}`]),
    ...constraints,
  ];
  if (required) return `    ${identifier}: ${type}${fieldArgs.length > 0 ? ` = Field(${fieldArgs.join(", ")})` : ""}`;
  return `    ${identifier}: ${type} | None = Field(default=None${fieldArgs.length > 0 ? `, ${fieldArgs.join(", ")}` : ""})`;
};
const pyFields = (schema, nestedName) =>
  Object.entries(schema.properties).map(([name, property]) =>
    pyField(name, property, (schema.required ?? []).includes(name), nestedName),
  ).join("\n");
const pyValidators = (schema) =>
  Object.entries(schema.properties).filter(([, property]) => property.uniqueItems).map(([name]) => `
    @field_validator("${name}")
    @classmethod
    def ${name}_are_unique(cls, value: list[str]) -> list[str]:
        if any(not item for item in value):
            raise ValueError("${name} entries must not be empty")
        if len(value) != len(set(value)):
            raise ValueError("${name} must contain unique values")
        return value
`).join("");

const apiModelNames = [
  "ExternalIdentifier",
  "Instrument",
  "CreateInstrumentRequest",
  "InstrumentStatusRequest",
  "InstrumentPage",
  "Portfolio",
  "PortfolioRequest",
  "PortfolioPage",
  "Account",
  "AccountRequest",
  "AccountPage",
  "SnapshotLineInput",
  "CreateSnapshotRequest",
  "SnapshotLine",
  "Snapshot",
  "SnapshotPage",
  "ValuationRequest",
  "FXPathEntry",
  "ValuationReason",
  "ValuationLine",
  "ValuationTotals",
  "ValuationRun",
];
const apiSchema = (name, seen = new Set()) => {
  if (seen.has(name)) throw new Error(`cyclic API schema composition: ${name}`);
  seen.add(name);
  const schema = source.components.schemas[name];
  if (!schema) throw new Error(`missing API schema: ${name}`);
  const properties = {};
  const required = new Set(schema.required ?? []);
  for (const part of schema.allOf ?? [schema]) {
    if (part.$ref) {
      const refName = part.$ref.split("/").at(-1);
      const resolved = apiSchema(refName, new Set(seen));
      Object.assign(properties, resolved.properties);
      for (const field of resolved.required) required.add(field);
      continue;
    }
    Object.assign(properties, part.properties ?? {});
    for (const field of part.required ?? []) required.add(field);
  }
  return { properties, required: [...required] };
};
const apiRefName = (property) => property.$ref?.split("/").at(-1);
const apiGoBaseType = (property, fieldName) => {
  const ref = apiRefName(property);
  if (ref) return ref;
  if (property.type === "array") {
    const itemRef = apiRefName(property.items ?? {});
    if (itemRef) return `[]${itemRef}`;
    return `[]${property.items?.type === "integer" ? "int" : property.items?.type === "number" ? "float64" : "string"}`;
  }
  if (Array.isArray(property.type) && property.type.includes("string")) return "string";
  if (property.type === "string") return "string";
  if (property.type === "integer") return "int";
  if (property.type === "number") return "float64";
  if (property.type === "boolean") return "bool";
  return "map[string]any";
};
const apiGoType = (property, fieldName, required) => {
  const type = apiGoBaseType(property, fieldName);
  if (required || type.startsWith("[]") || type.startsWith("map[")) return type;
  return `*${type}`;
};
const apiTsType = (property) => {
  const ref = apiRefName(property);
  if (ref) return ref;
  if (property.type === "array") {
    const itemRef = apiRefName(property.items ?? {});
    if (itemRef) return `${itemRef}[]`;
    return `${property.items?.type === "integer" || property.items?.type === "number" ? "number" : "string"}[]`;
  }
  if (Array.isArray(property.type) && property.type.includes("string")) return "string | null";
  if (property.type === "string") return property.enum?.map((value) => JSON.stringify(value)).join(" | ") || "string";
  if (property.type === "integer" || property.type === "number") return "number";
  if (property.type === "boolean") return "boolean";
  return "Record<string, unknown>";
};
const apiPyType = (property) => {
  const ref = apiRefName(property);
  if (ref) return ref;
  if (property.type === "array") {
    const itemRef = apiRefName(property.items ?? {});
    if (itemRef) return `list[${itemRef}]`;
    return `list[${property.items?.type === "integer" ? "int" : property.items?.type === "number" ? "float" : "str"}]`;
  }
  if (Array.isArray(property.type) && property.type.includes("string")) return "str | None";
  if (property.type === "string") return property.enum ? `Literal[${property.enum.map((value) => JSON.stringify(value)).join(", ")}]` : "str";
  if (property.type === "integer") return "int";
  if (property.type === "number") return "float";
  if (property.type === "boolean") return "bool";
  return "dict[str, Any]";
};
const apiGoFields = (name) => {
  const schema = apiSchema(name);
  return Object.entries(schema.properties).map(([field, property]) => {
    const required = schema.required.includes(field);
    return `\t${pascal(field)} ${apiGoType(property, `${name}${pascal(field)}`, required)} \`json:"${field}${required ? "" : ",omitempty"}"\``;
  }).join("\n");
};
const apiTsFields = (name) => {
  const schema = apiSchema(name);
  return Object.entries(schema.properties).map(([field, property]) =>
    `  ${field}${schema.required.includes(field) ? "" : "?"}: ${apiTsType(property)};`,
  ).join("\n");
};
const apiPyFields = (name) => {
  const schema = apiSchema(name);
  return Object.entries(schema.properties).map(([field, property]) => {
    const required = schema.required.includes(field);
    const identifier = pyIdentifier(field);
    const alias = identifier === field ? "" : ` = Field(alias=${JSON.stringify(field)})`;
    return `    ${identifier}: ${apiPyType(property)}${required ? alias : ` | None${alias || " = None"}`}`;
  }).join("\n");
};
const apiGoModels = apiModelNames.map((name) => `type ${name} struct {\n${apiGoFields(name)}\n}`).join("\n\n");
const apiTsModels = apiModelNames.map((name) => `export interface ${name} {\n${apiTsFields(name)}\n}`).join("\n\n");
const apiPyModels = apiModelNames.map((name) => `class ${name}(ContractModel):\n${apiPyFields(name)}`).join("\n\n");

const write = async (relativePath, contents) => {
  const target = resolve(root, relativePath);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, contents, "utf8");
};

const goErrorFields = goFields(errorSchema, undefined, "ErrorEnvelope");
const goPageFields = goFields(source.components.schemas.PageMeta, undefined, "PageMeta");
const goJobFields = goFields(jobSchema, undefined, "JobEnvelope");
const goResultFields = goFields(resultSchema, undefined, "ResultEnvelope");
const goImportColumnFields = goFields(manifestSchema.properties.columns.items, undefined, "ImportColumn");
const goImportManifestFields = goFields(manifestSchema, "ImportColumn", "ImportManifest");
const goUnknownFields = goFields(versionErrorSchema.properties.details, undefined, "UnknownSchemaVersionDetails");
const goNamedDeclarations = [...goNamedTypes.entries()].map(([name, values]) => {
  const constants = values.map((value) => `\t${name}${goValueIdentifier(value)} ${name} = ${JSON.stringify(value)}`).join("\n");
  return `type ${name} string\n\nconst (\n${constants}\n)`;
}).join("\n\n");

const go = `${header}// AtlasRisk contract models for ${source.info.title}.
package contracts

const SupportedSchemaVersion = "${schemaVersion}"
const UnknownSchemaVersionCode = "ATLAS_UNKNOWN_SCHEMA_VERSION"

${goNamedDeclarations}

type ErrorEnvelope struct {
${goErrorFields}
}

type PageMeta struct {
${goPageFields}
}

type JobEnvelope struct {
${goJobFields}
}

type ResultEnvelope struct {
${goResultFields}
}

type ImportColumn struct {
${goImportColumnFields}
}

type ImportManifest struct {
${goImportManifestFields}
}

type UnknownSchemaVersionDetails struct {
${goUnknownFields}
}

${apiGoModels}
`;

const typescript = `${header}export const SUPPORTED_SCHEMA_VERSION = "${schemaVersion}" as const;
export const UNKNOWN_SCHEMA_VERSION_CODE = "ATLAS_UNKNOWN_SCHEMA_VERSION" as const;

export interface ErrorEnvelope {
${tsFields(errorSchema)}
}

export interface PageMeta {
${tsFields(source.components.schemas.PageMeta)}
}

export interface JobEnvelope {
${tsFields(jobSchema)}
}

export type ResultStatus = ${tsType(resultSchema.properties.status)};
export type DataQuality = ${tsType(resultSchema.properties.data_quality)};

export interface ResultEnvelope {
${tsFields(resultSchema)}
}

export type ImportColumnType = ${tsType(manifestSchema.properties.columns.items.properties.data_type)};
export interface ImportColumn {
${tsFields(manifestSchema.properties.columns.items)}
}
export interface ImportManifest {
${tsFields(manifestSchema, "ImportColumn")}
}

export interface UnknownSchemaVersionDetails {
${tsFields(versionErrorSchema.properties.details)}
}

${apiTsModels}
`;

const python = `${pythonHeader}from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

SUPPORTED_SCHEMA_VERSION = "${schemaVersion}"
UNKNOWN_SCHEMA_VERSION_CODE = "ATLAS_UNKNOWN_SCHEMA_VERSION"


class ContractModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class ErrorEnvelope(ContractModel):
${pyFields(errorSchema)}


class PageMeta(ContractModel):
${pyFields(source.components.schemas.PageMeta)}


class JobEnvelope(ContractModel):
${pyFields(jobSchema)}
${pyValidators(jobSchema)}


class ResultEnvelope(ContractModel):
${pyFields(resultSchema)}
${pyValidators(resultSchema)}


class ImportColumn(ContractModel):
${pyFields(manifestSchema.properties.columns.items)}


class ImportManifest(ContractModel):
${pyFields(manifestSchema, "ImportColumn")}


class UnknownSchemaVersionDetails(ContractModel):
${pyFields(versionErrorSchema.properties.details)}


${apiPyModels}
`;

await write("contracts/generated/go/contracts.go", go);
await write("contracts/generated/typescript/contracts.ts", typescript);
await write("contracts/generated/python/contracts.py", python);
await write(
  "contracts/generated/python/__init__.py",
  `${pythonHeader}from .contracts import (\n${["ErrorEnvelope", "ImportColumn", "ImportManifest", "JobEnvelope", "PageMeta", "ResultEnvelope", "UnknownSchemaVersionDetails", ...apiModelNames].map((name) => `    ${name},`).join("\n")}\n)\n\n__all__ = [\n${["ErrorEnvelope", "ImportColumn", "ImportManifest", "JobEnvelope", "PageMeta", "ResultEnvelope", "UnknownSchemaVersionDetails", ...apiModelNames].map((name) => `    "${name}",`).join("\n")}\n]\n`,
);
await run("gofmt", ["-w", resolve(root, "contracts/generated/go/contracts.go")]);
console.log("Generated Go, TypeScript, and Python contract models.");
