// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDataSourceByCode = `-- name: GetDataSourceByCode :one
SELECT id, code, name, adapter_version, metadata, created_at FROM data_sources
WHERE code = $1
`

func (q *Queries) GetDataSourceByCode(ctx context.Context, code string) (DataSource, error) {
	row := q.db.QueryRow(ctx, getDataSourceByCode, code)
	var i DataSource
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AdapterVersion,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getDataset = `-- name: GetDataset :one
SELECT id, source_id, external_key, name, metadata, created_at FROM datasets
WHERE id = $1
`

func (q *Queries) GetDataset(ctx context.Context, id pgtype.UUID) (Dataset, error) {
	row := q.db.QueryRow(ctx, getDataset, id)
	var i Dataset
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ExternalKey,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getDatasetByExternalKey = `-- name: GetDatasetByExternalKey :one
SELECT id, source_id, external_key, name, metadata, created_at FROM datasets
WHERE source_id = $1 AND external_key = $2
`

type GetDatasetByExternalKeyParams struct {
	SourceID    pgtype.UUID `json:"source_id"`
	ExternalKey string      `json:"external_key"`
}

func (q *Queries) GetDatasetByExternalKey(ctx context.Context, arg GetDatasetByExternalKeyParams) (Dataset, error) {
	row := q.db.QueryRow(ctx, getDatasetByExternalKey, arg.SourceID, arg.ExternalKey)
	var i Dataset
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ExternalKey,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getFXQuoteRevision = `-- name: GetFXQuoteRevision :one
SELECT id, base_currency, quote_currency, observation_time, rate, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM fx_quote_revisions
WHERE id = $1
`

func (q *Queries) GetFXQuoteRevision(ctx context.Context, id pgtype.UUID) (FxQuoteRevision, error) {
	row := q.db.QueryRow(ctx, getFXQuoteRevision, id)
	var i FxQuoteRevision
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.ObservationTime,
		&i.Rate,
		&i.SourceKnownAt,
		&i.SystemKnownAt,
		&i.KnowledgeTimeBasis,
		&i.RawObjectID,
		&i.QualityFlags,
	)
	return i, err
}

const getInstrument = `-- name: GetInstrument :one
SELECT id, canonical_symbol, instrument_type, native_currency, external_ids, status, created_at FROM instruments
WHERE id = $1
`

func (q *Queries) GetInstrument(ctx context.Context, id pgtype.UUID) (Instrument, error) {
	row := q.db.QueryRow(ctx, getInstrument, id)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.CanonicalSymbol,
		&i.InstrumentType,
		&i.NativeCurrency,
		&i.ExternalIds,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getInstrumentBySymbol = `-- name: GetInstrumentBySymbol :one
SELECT id, canonical_symbol, instrument_type, native_currency, external_ids, status, created_at FROM instruments
WHERE canonical_symbol = $1
`

func (q *Queries) GetInstrumentBySymbol(ctx context.Context, canonicalSymbol string) (Instrument, error) {
	row := q.db.QueryRow(ctx, getInstrumentBySymbol, canonicalSymbol)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.CanonicalSymbol,
		&i.InstrumentType,
		&i.NativeCurrency,
		&i.ExternalIds,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getObservationRevision = `-- name: GetObservationRevision :one
SELECT id, series_id, observation_time, value, value_text, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM observation_revisions
WHERE id = $1
`

func (q *Queries) GetObservationRevision(ctx context.Context, id pgtype.UUID) (ObservationRevision, error) {
	row := q.db.QueryRow(ctx, getObservationRevision, id)
	var i ObservationRevision
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.ObservationTime,
		&i.Value,
		&i.ValueText,
		&i.SourceKnownAt,
		&i.SystemKnownAt,
		&i.KnowledgeTimeBasis,
		&i.RawObjectID,
		&i.QualityFlags,
	)
	return i, err
}

const getPriceRevision = `-- name: GetPriceRevision :one
SELECT id, instrument_id, quote_currency, observation_time, price, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM price_revisions
WHERE id = $1
`

func (q *Queries) GetPriceRevision(ctx context.Context, id pgtype.UUID) (PriceRevision, error) {
	row := q.db.QueryRow(ctx, getPriceRevision, id)
	var i PriceRevision
	err := row.Scan(
		&i.ID,
		&i.InstrumentID,
		&i.QuoteCurrency,
		&i.ObservationTime,
		&i.Price,
		&i.SourceKnownAt,
		&i.SystemKnownAt,
		&i.KnowledgeTimeBasis,
		&i.RawObjectID,
		&i.QualityFlags,
	)
	return i, err
}

const getRawObjectBySHA256 = `-- name: GetRawObjectBySHA256 :one
SELECT id, content_sha256, object_key, media_type, byte_length, retrieved_at, request_uri, request_metadata, ingestion_run_id, created_at FROM raw_objects
WHERE content_sha256 = $1
`

func (q *Queries) GetRawObjectBySHA256(ctx context.Context, contentSha256 string) (RawObject, error) {
	row := q.db.QueryRow(ctx, getRawObjectBySHA256, contentSha256)
	var i RawObject
	err := row.Scan(
		&i.ID,
		&i.ContentSha256,
		&i.ObjectKey,
		&i.MediaType,
		&i.ByteLength,
		&i.RetrievedAt,
		&i.RequestUri,
		&i.RequestMetadata,
		&i.IngestionRunID,
		&i.CreatedAt,
	)
	return i, err
}

const getSeries = `-- name: GetSeries :one
SELECT id, dataset_id, source_code, name, unit, frequency, seasonal_adjustment, source_timezone, freshness_policy, created_at FROM series
WHERE id = $1
`

func (q *Queries) GetSeries(ctx context.Context, id pgtype.UUID) (Series, error) {
	row := q.db.QueryRow(ctx, getSeries, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.SourceCode,
		&i.Name,
		&i.Unit,
		&i.Frequency,
		&i.SeasonalAdjustment,
		&i.SourceTimezone,
		&i.FreshnessPolicy,
		&i.CreatedAt,
	)
	return i, err
}

const getSeriesBySourceCode = `-- name: GetSeriesBySourceCode :one
SELECT id, dataset_id, source_code, name, unit, frequency, seasonal_adjustment, source_timezone, freshness_policy, created_at FROM series
WHERE dataset_id = $1 AND source_code = $2
`

type GetSeriesBySourceCodeParams struct {
	DatasetID  pgtype.UUID `json:"dataset_id"`
	SourceCode string      `json:"source_code"`
}

func (q *Queries) GetSeriesBySourceCode(ctx context.Context, arg GetSeriesBySourceCodeParams) (Series, error) {
	row := q.db.QueryRow(ctx, getSeriesBySourceCode, arg.DatasetID, arg.SourceCode)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.SourceCode,
		&i.Name,
		&i.Unit,
		&i.Frequency,
		&i.SeasonalAdjustment,
		&i.SourceTimezone,
		&i.FreshnessPolicy,
		&i.CreatedAt,
	)
	return i, err
}

const insertDataSource = `-- name: InsertDataSource :execrows
INSERT INTO data_sources (code, name, adapter_version, metadata)
VALUES ($1, $2, $3, $4)
ON CONFLICT (code) DO NOTHING
`

type InsertDataSourceParams struct {
	Code           string `json:"code"`
	Name           string `json:"name"`
	AdapterVersion string `json:"adapter_version"`
	Metadata       []byte `json:"metadata"`
}

func (q *Queries) InsertDataSource(ctx context.Context, arg InsertDataSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDataSource,
		arg.Code,
		arg.Name,
		arg.AdapterVersion,
		arg.Metadata,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertDataset = `-- name: InsertDataset :execrows
INSERT INTO datasets (source_id, external_key, name, metadata)
VALUES ($1, $2, $3, $4)
ON CONFLICT (source_id, external_key) DO NOTHING
`

type InsertDatasetParams struct {
	SourceID    pgtype.UUID `json:"source_id"`
	ExternalKey string      `json:"external_key"`
	Name        string      `json:"name"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) InsertDataset(ctx context.Context, arg InsertDatasetParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDataset,
		arg.SourceID,
		arg.ExternalKey,
		arg.Name,
		arg.Metadata,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertFXQuoteRevision = `-- name: InsertFXQuoteRevision :execrows
INSERT INTO fx_quote_revisions (
    base_currency, quote_currency, observation_time, rate, source_known_at,
    knowledge_time_basis, raw_object_id, quality_flags
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (base_currency, quote_currency, observation_time, rate, source_known_at, raw_object_id)
DO NOTHING
`

type InsertFXQuoteRevisionParams struct {
	BaseCurrency       string             `json:"base_currency"`
	QuoteCurrency      string             `json:"quote_currency"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Rate               pgtype.Numeric     `json:"rate"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

func (q *Queries) InsertFXQuoteRevision(ctx context.Context, arg InsertFXQuoteRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertFXQuoteRevision,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.ObservationTime,
		arg.Rate,
		arg.SourceKnownAt,
		arg.KnowledgeTimeBasis,
		arg.RawObjectID,
		arg.QualityFlags,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertInstrument = `-- name: InsertInstrument :execrows
INSERT INTO instruments (
    canonical_symbol, instrument_type, native_currency, external_ids, status
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (canonical_symbol) DO NOTHING
`

type InsertInstrumentParams struct {
	CanonicalSymbol string `json:"canonical_symbol"`
	InstrumentType  string `json:"instrument_type"`
	NativeCurrency  string `json:"native_currency"`
	ExternalIds     []byte `json:"external_ids"`
	Status          string `json:"status"`
}

func (q *Queries) InsertInstrument(ctx context.Context, arg InsertInstrumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInstrument,
		arg.CanonicalSymbol,
		arg.InstrumentType,
		arg.NativeCurrency,
		arg.ExternalIds,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertObservationRevision = `-- name: InsertObservationRevision :execrows
INSERT INTO observation_revisions (
    series_id, observation_time, value, value_text, source_known_at,
    knowledge_time_basis, raw_object_id, quality_flags
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (series_id, observation_time, value, value_text, source_known_at, raw_object_id)
DO NOTHING
`

type InsertObservationRevisionParams struct {
	SeriesID           pgtype.UUID        `json:"series_id"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Value              pgtype.Numeric     `json:"value"`
	ValueText          *string            `json:"value_text"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

func (q *Queries) InsertObservationRevision(ctx context.Context, arg InsertObservationRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertObservationRevision,
		arg.SeriesID,
		arg.ObservationTime,
		arg.Value,
		arg.ValueText,
		arg.SourceKnownAt,
		arg.KnowledgeTimeBasis,
		arg.RawObjectID,
		arg.QualityFlags,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPriceRevision = `-- name: InsertPriceRevision :execrows
INSERT INTO price_revisions (
    instrument_id, quote_currency, observation_time, price, source_known_at,
    knowledge_time_basis, raw_object_id, quality_flags
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (instrument_id, quote_currency, observation_time, price, source_known_at, raw_object_id)
DO NOTHING
`

type InsertPriceRevisionParams struct {
	InstrumentID       pgtype.UUID        `json:"instrument_id"`
	QuoteCurrency      string             `json:"quote_currency"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Price              pgtype.Numeric     `json:"price"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

func (q *Queries) InsertPriceRevision(ctx context.Context, arg InsertPriceRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPriceRevision,
		arg.InstrumentID,
		arg.QuoteCurrency,
		arg.ObservationTime,
		arg.Price,
		arg.SourceKnownAt,
		arg.KnowledgeTimeBasis,
		arg.RawObjectID,
		arg.QualityFlags,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRawObject = `-- name: InsertRawObject :execrows
INSERT INTO raw_objects (
    content_sha256, object_key, media_type, byte_length, retrieved_at,
    request_uri, request_metadata, ingestion_run_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (content_sha256) DO NOTHING
`

type InsertRawObjectParams struct {
	ContentSha256   string             `json:"content_sha256"`
	ObjectKey       string             `json:"object_key"`
	MediaType       string             `json:"media_type"`
	ByteLength      int64              `json:"byte_length"`
	RetrievedAt     pgtype.Timestamptz `json:"retrieved_at"`
	RequestUri      *string            `json:"request_uri"`
	RequestMetadata []byte             `json:"request_metadata"`
	IngestionRunID  pgtype.UUID        `json:"ingestion_run_id"`
}

func (q *Queries) InsertRawObject(ctx context.Context, arg InsertRawObjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRawObject,
		arg.ContentSha256,
		arg.ObjectKey,
		arg.MediaType,
		arg.ByteLength,
		arg.RetrievedAt,
		arg.RequestUri,
		arg.RequestMetadata,
		arg.IngestionRunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSeries = `-- name: InsertSeries :execrows
INSERT INTO series (
    dataset_id, source_code, name, unit, frequency, seasonal_adjustment,
    source_timezone, freshness_policy
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (dataset_id, source_code) DO NOTHING
`

type InsertSeriesParams struct {
	DatasetID          pgtype.UUID `json:"dataset_id"`
	SourceCode         string      `json:"source_code"`
	Name               string      `json:"name"`
	Unit               string      `json:"unit"`
	Frequency          string      `json:"frequency"`
	SeasonalAdjustment *string     `json:"seasonal_adjustment"`
	SourceTimezone     *string     `json:"source_timezone"`
	FreshnessPolicy    []byte      `json:"freshness_policy"`
}

func (q *Queries) InsertSeries(ctx context.Context, arg InsertSeriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSeries,
		arg.DatasetID,
		arg.SourceCode,
		arg.Name,
		arg.Unit,
		arg.Frequency,
		arg.SeasonalAdjustment,
		arg.SourceTimezone,
		arg.FreshnessPolicy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFXQuoteRevisions = `-- name: ListFXQuoteRevisions :many
SELECT id, base_currency, quote_currency, observation_time, rate, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM fx_quote_revisions
WHERE base_currency = $1
  AND quote_currency = $2
  AND observation_time >= $3
  AND observation_time < $4
ORDER BY observation_time, system_known_at, id
`

type ListFXQuoteRevisionsParams struct {
	BaseCurrency      string             `json:"base_currency"`
	QuoteCurrency     string             `json:"quote_currency"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
}

func (q *Queries) ListFXQuoteRevisions(ctx context.Context, arg ListFXQuoteRevisionsParams) ([]FxQuoteRevision, error) {
	rows, err := q.db.Query(ctx, listFXQuoteRevisions,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.ObservationTime,
		arg.ObservationTime_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FxQuoteRevision{}
	for rows.Next() {
		var i FxQuoteRevision
		if err := rows.Scan(
			&i.ID,
			&i.BaseCurrency,
			&i.QuoteCurrency,
			&i.ObservationTime,
			&i.Rate,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFXQuotesSourceAsOf = `-- name: ListFXQuotesSourceAsOf :many
SELECT id, base_currency, quote_currency, observation_time, rate, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM (
    SELECT DISTINCT ON (base_currency, quote_currency, observation_time) id, base_currency, quote_currency, observation_time, rate, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags
    FROM fx_quote_revisions
    WHERE base_currency = $1
      AND quote_currency = $2
      AND observation_time >= $3
      AND observation_time < $4
      AND source_known_at IS NOT NULL
      AND source_known_at <= $5
    ORDER BY base_currency, quote_currency, observation_time, source_known_at DESC, system_known_at DESC, id DESC
) AS revisions
ORDER BY observation_time, id
`

type ListFXQuotesSourceAsOfParams struct {
	BaseCurrency      string             `json:"base_currency"`
	QuoteCurrency     string             `json:"quote_currency"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
	SourceKnownAt     pgtype.Timestamptz `json:"source_known_at"`
}

func (q *Queries) ListFXQuotesSourceAsOf(ctx context.Context, arg ListFXQuotesSourceAsOfParams) ([]FxQuoteRevision, error) {
	rows, err := q.db.Query(ctx, listFXQuotesSourceAsOf,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.ObservationTime,
		arg.ObservationTime_2,
		arg.SourceKnownAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FxQuoteRevision{}
	for rows.Next() {
		var i FxQuoteRevision
		if err := rows.Scan(
			&i.ID,
			&i.BaseCurrency,
			&i.QuoteCurrency,
			&i.ObservationTime,
			&i.Rate,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFXQuotesSystemAsOf = `-- name: ListFXQuotesSystemAsOf :many
SELECT id, base_currency, quote_currency, observation_time, rate, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM (
    SELECT DISTINCT ON (base_currency, quote_currency, observation_time) id, base_currency, quote_currency, observation_time, rate, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags
    FROM fx_quote_revisions
    WHERE base_currency = $1
      AND quote_currency = $2
      AND observation_time >= $3
      AND observation_time < $4
      AND system_known_at <= $5
    ORDER BY base_currency, quote_currency, observation_time, system_known_at DESC, id DESC
) AS revisions
ORDER BY observation_time, id
`

type ListFXQuotesSystemAsOfParams struct {
	BaseCurrency      string             `json:"base_currency"`
	QuoteCurrency     string             `json:"quote_currency"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
	SystemKnownAt     pgtype.Timestamptz `json:"system_known_at"`
}

func (q *Queries) ListFXQuotesSystemAsOf(ctx context.Context, arg ListFXQuotesSystemAsOfParams) ([]FxQuoteRevision, error) {
	rows, err := q.db.Query(ctx, listFXQuotesSystemAsOf,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.ObservationTime,
		arg.ObservationTime_2,
		arg.SystemKnownAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FxQuoteRevision{}
	for rows.Next() {
		var i FxQuoteRevision
		if err := rows.Scan(
			&i.ID,
			&i.BaseCurrency,
			&i.QuoteCurrency,
			&i.ObservationTime,
			&i.Rate,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationRevisions = `-- name: ListObservationRevisions :many
SELECT id, series_id, observation_time, value, value_text, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM observation_revisions
WHERE series_id = $1
  AND observation_time >= $2
  AND observation_time < $3
ORDER BY observation_time, system_known_at, id
`

type ListObservationRevisionsParams struct {
	SeriesID          pgtype.UUID        `json:"series_id"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
}

func (q *Queries) ListObservationRevisions(ctx context.Context, arg ListObservationRevisionsParams) ([]ObservationRevision, error) {
	rows, err := q.db.Query(ctx, listObservationRevisions, arg.SeriesID, arg.ObservationTime, arg.ObservationTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationRevision{}
	for rows.Next() {
		var i ObservationRevision
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ObservationTime,
			&i.Value,
			&i.ValueText,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsSourceAsOf = `-- name: ListObservationsSourceAsOf :many
SELECT id, series_id, observation_time, value, value_text, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM (
    SELECT DISTINCT ON (observation_time) id, series_id, observation_time, value, value_text, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags
    FROM observation_revisions
    WHERE series_id = $1
      AND observation_time >= $2
      AND observation_time < $3
      AND source_known_at IS NOT NULL
      AND source_known_at <= $4
    ORDER BY observation_time, source_known_at DESC, system_known_at DESC, id DESC
) AS revisions
ORDER BY observation_time, id
`

type ListObservationsSourceAsOfParams struct {
	SeriesID          pgtype.UUID        `json:"series_id"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
	SourceKnownAt     pgtype.Timestamptz `json:"source_known_at"`
}

func (q *Queries) ListObservationsSourceAsOf(ctx context.Context, arg ListObservationsSourceAsOfParams) ([]ObservationRevision, error) {
	rows, err := q.db.Query(ctx, listObservationsSourceAsOf,
		arg.SeriesID,
		arg.ObservationTime,
		arg.ObservationTime_2,
		arg.SourceKnownAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationRevision{}
	for rows.Next() {
		var i ObservationRevision
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ObservationTime,
			&i.Value,
			&i.ValueText,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsSystemAsOf = `-- name: ListObservationsSystemAsOf :many
SELECT id, series_id, observation_time, value, value_text, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM (
    SELECT DISTINCT ON (observation_time) id, series_id, observation_time, value, value_text, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags
    FROM observation_revisions
    WHERE series_id = $1
      AND observation_time >= $2
      AND observation_time < $3
      AND system_known_at <= $4
    ORDER BY observation_time, system_known_at DESC, id DESC
) AS revisions
ORDER BY observation_time, id
`

type ListObservationsSystemAsOfParams struct {
	SeriesID          pgtype.UUID        `json:"series_id"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
	SystemKnownAt     pgtype.Timestamptz `json:"system_known_at"`
}

func (q *Queries) ListObservationsSystemAsOf(ctx context.Context, arg ListObservationsSystemAsOfParams) ([]ObservationRevision, error) {
	rows, err := q.db.Query(ctx, listObservationsSystemAsOf,
		arg.SeriesID,
		arg.ObservationTime,
		arg.ObservationTime_2,
		arg.SystemKnownAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationRevision{}
	for rows.Next() {
		var i ObservationRevision
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ObservationTime,
			&i.Value,
			&i.ValueText,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceRevisions = `-- name: ListPriceRevisions :many
SELECT id, instrument_id, quote_currency, observation_time, price, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM price_revisions
WHERE instrument_id = $1
  AND quote_currency = $2
  AND observation_time >= $3
  AND observation_time < $4
ORDER BY observation_time, system_known_at, id
`

type ListPriceRevisionsParams struct {
	InstrumentID      pgtype.UUID        `json:"instrument_id"`
	QuoteCurrency     string             `json:"quote_currency"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
}

func (q *Queries) ListPriceRevisions(ctx context.Context, arg ListPriceRevisionsParams) ([]PriceRevision, error) {
	rows, err := q.db.Query(ctx, listPriceRevisions,
		arg.InstrumentID,
		arg.QuoteCurrency,
		arg.ObservationTime,
		arg.ObservationTime_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceRevision{}
	for rows.Next() {
		var i PriceRevision
		if err := rows.Scan(
			&i.ID,
			&i.InstrumentID,
			&i.QuoteCurrency,
			&i.ObservationTime,
			&i.Price,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricesSourceAsOf = `-- name: ListPricesSourceAsOf :many
SELECT id, instrument_id, quote_currency, observation_time, price, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM (
    SELECT DISTINCT ON (quote_currency, observation_time) id, instrument_id, quote_currency, observation_time, price, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags
    FROM price_revisions
    WHERE instrument_id = $1
      AND quote_currency = $2
      AND observation_time >= $3
      AND observation_time < $4
      AND source_known_at IS NOT NULL
      AND source_known_at <= $5
    ORDER BY quote_currency, observation_time, source_known_at DESC, system_known_at DESC, id DESC
) AS revisions
ORDER BY observation_time, id
`

type ListPricesSourceAsOfParams struct {
	InstrumentID      pgtype.UUID        `json:"instrument_id"`
	QuoteCurrency     string             `json:"quote_currency"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
	SourceKnownAt     pgtype.Timestamptz `json:"source_known_at"`
}

func (q *Queries) ListPricesSourceAsOf(ctx context.Context, arg ListPricesSourceAsOfParams) ([]PriceRevision, error) {
	rows, err := q.db.Query(ctx, listPricesSourceAsOf,
		arg.InstrumentID,
		arg.QuoteCurrency,
		arg.ObservationTime,
		arg.ObservationTime_2,
		arg.SourceKnownAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceRevision{}
	for rows.Next() {
		var i PriceRevision
		if err := rows.Scan(
			&i.ID,
			&i.InstrumentID,
			&i.QuoteCurrency,
			&i.ObservationTime,
			&i.Price,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricesSystemAsOf = `-- name: ListPricesSystemAsOf :many
SELECT id, instrument_id, quote_currency, observation_time, price, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM (
    SELECT DISTINCT ON (quote_currency, observation_time) id, instrument_id, quote_currency, observation_time, price, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags
    FROM price_revisions
    WHERE instrument_id = $1
      AND quote_currency = $2
      AND observation_time >= $3
      AND observation_time < $4
      AND system_known_at <= $5
    ORDER BY quote_currency, observation_time, system_known_at DESC, id DESC
) AS revisions
ORDER BY observation_time, id
`

type ListPricesSystemAsOfParams struct {
	InstrumentID      pgtype.UUID        `json:"instrument_id"`
	QuoteCurrency     string             `json:"quote_currency"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
	SystemKnownAt     pgtype.Timestamptz `json:"system_known_at"`
}

func (q *Queries) ListPricesSystemAsOf(ctx context.Context, arg ListPricesSystemAsOfParams) ([]PriceRevision, error) {
	rows, err := q.db.Query(ctx, listPricesSystemAsOf,
		arg.InstrumentID,
		arg.QuoteCurrency,
		arg.ObservationTime,
		arg.ObservationTime_2,
		arg.SystemKnownAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceRevision{}
	for rows.Next() {
		var i PriceRevision
		if err := rows.Scan(
			&i.ID,
			&i.InstrumentID,
			&i.QuoteCurrency,
			&i.ObservationTime,
			&i.Price,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesByDataset = `-- name: ListSeriesByDataset :many
SELECT id, dataset_id, source_code, name, unit, frequency, seasonal_adjustment, source_timezone, freshness_policy, created_at FROM series
WHERE dataset_id = $1
ORDER BY source_code, id
`

func (q *Queries) ListSeriesByDataset(ctx context.Context, datasetID pgtype.UUID) ([]Series, error) {
	rows, err := q.db.Query(ctx, listSeriesByDataset, datasetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.DatasetID,
			&i.SourceCode,
			&i.Name,
			&i.Unit,
			&i.Frequency,
			&i.SeasonalAdjustment,
			&i.SourceTimezone,
			&i.FreshnessPolicy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
