// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DataSource struct {
	ID             pgtype.UUID        `json:"id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	AdapterVersion string             `json:"adapter_version"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Dataset struct {
	ID          pgtype.UUID        `json:"id"`
	SourceID    pgtype.UUID        `json:"source_id"`
	ExternalKey string             `json:"external_key"`
	Name        string             `json:"name"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type FxQuoteRevision struct {
	ID                 pgtype.UUID        `json:"id"`
	BaseCurrency       string             `json:"base_currency"`
	QuoteCurrency      string             `json:"quote_currency"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Rate               pgtype.Numeric     `json:"rate"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

type IngestionRun struct {
	ID             pgtype.UUID        `json:"id"`
	SourceID       pgtype.UUID        `json:"source_id"`
	DatasetID      pgtype.UUID        `json:"dataset_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	AdapterVersion string             `json:"adapter_version"`
	RequestedFrom  pgtype.Timestamptz `json:"requested_from"`
	RequestedTo    pgtype.Timestamptz `json:"requested_to"`
	Status         string             `json:"status"`
	Coverage       []byte             `json:"coverage"`
	ErrorCode      *string            `json:"error_code"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type Instrument struct {
	ID              pgtype.UUID        `json:"id"`
	CanonicalSymbol string             `json:"canonical_symbol"`
	InstrumentType  string             `json:"instrument_type"`
	NativeCurrency  string             `json:"native_currency"`
	ExternalIds     []byte             `json:"external_ids"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type LatestFxQuoteRevision struct {
	ID                 pgtype.UUID        `json:"id"`
	BaseCurrency       string             `json:"base_currency"`
	QuoteCurrency      string             `json:"quote_currency"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Rate               pgtype.Numeric     `json:"rate"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

type LatestObservationRevision struct {
	ID                 pgtype.UUID        `json:"id"`
	SeriesID           pgtype.UUID        `json:"series_id"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Value              pgtype.Numeric     `json:"value"`
	ValueText          *string            `json:"value_text"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

type LatestPriceRevision struct {
	ID                 pgtype.UUID        `json:"id"`
	InstrumentID       pgtype.UUID        `json:"instrument_id"`
	QuoteCurrency      string             `json:"quote_currency"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Price              pgtype.Numeric     `json:"price"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

type ObservationRevision struct {
	ID                 pgtype.UUID        `json:"id"`
	SeriesID           pgtype.UUID        `json:"series_id"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Value              pgtype.Numeric     `json:"value"`
	ValueText          *string            `json:"value_text"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

type PriceRevision struct {
	ID                 pgtype.UUID        `json:"id"`
	InstrumentID       pgtype.UUID        `json:"instrument_id"`
	QuoteCurrency      string             `json:"quote_currency"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Price              pgtype.Numeric     `json:"price"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

type RawObject struct {
	ID              pgtype.UUID        `json:"id"`
	ContentSha256   string             `json:"content_sha256"`
	ObjectKey       string             `json:"object_key"`
	MediaType       string             `json:"media_type"`
	ByteLength      int64              `json:"byte_length"`
	RetrievedAt     pgtype.Timestamptz `json:"retrieved_at"`
	RequestUri      *string            `json:"request_uri"`
	RequestMetadata []byte             `json:"request_metadata"`
	IngestionRunID  pgtype.UUID        `json:"ingestion_run_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Series struct {
	ID                 pgtype.UUID        `json:"id"`
	DatasetID          pgtype.UUID        `json:"dataset_id"`
	SourceCode         string             `json:"source_code"`
	Name               string             `json:"name"`
	Unit               string             `json:"unit"`
	Frequency          string             `json:"frequency"`
	SeasonalAdjustment *string            `json:"seasonal_adjustment"`
	SourceTimezone     *string            `json:"source_timezone"`
	FreshnessPolicy    []byte             `json:"freshness_policy"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
