// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          pgtype.UUID        `json:"id"`
	PortfolioID pgtype.UUID        `json:"portfolio_id"`
	Name        string             `json:"name"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CollectorSchedule struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Provider           string             `json:"provider"`
	SourceID           pgtype.UUID        `json:"source_id"`
	DatasetID          pgtype.UUID        `json:"dataset_id"`
	SeriesID           pgtype.UUID        `json:"series_id"`
	InstrumentID       pgtype.UUID        `json:"instrument_id"`
	Configuration      []byte             `json:"configuration"`
	RequestFingerprint string             `json:"request_fingerprint"`
	IntervalSeconds    int32              `json:"interval_seconds"`
	LeaseSeconds       int32              `json:"lease_seconds"`
	NextRunAt          pgtype.Timestamptz `json:"next_run_at"`
	RetryAvailableAt   pgtype.Timestamptz `json:"retry_available_at"`
	Active             bool               `json:"active"`
	LeaseOwner         *string            `json:"lease_owner"`
	LeaseToken         pgtype.UUID        `json:"lease_token"`
	LeaseExpiresAt     pgtype.Timestamptz `json:"lease_expires_at"`
	Checkpoint         []byte             `json:"checkpoint"`
	AttemptCount       int32              `json:"attempt_count"`
	MaxAttempts        int32              `json:"max_attempts"`
	LastRunID          pgtype.UUID        `json:"last_run_id"`
	LastErrorCode      *string            `json:"last_error_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type DataSource struct {
	ID             pgtype.UUID        `json:"id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	AdapterVersion string             `json:"adapter_version"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Dataset struct {
	ID          pgtype.UUID        `json:"id"`
	SourceID    pgtype.UUID        `json:"source_id"`
	ExternalKey string             `json:"external_key"`
	Name        string             `json:"name"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Decision struct {
	ID                     pgtype.UUID        `json:"id"`
	AccountID              pgtype.UUID        `json:"account_id"`
	Thesis                 string             `json:"thesis"`
	Alternatives           []byte             `json:"alternatives"`
	EvidenceReferences     []byte             `json:"evidence_references"`
	InvalidationConditions []byte             `json:"invalidation_conditions"`
	HorizonStart           pgtype.Timestamptz `json:"horizon_start"`
	HorizonEnd             pgtype.Timestamptz `json:"horizon_end"`
	RiskBudgetAmount       pgtype.Numeric     `json:"risk_budget_amount"`
	RiskBudgetCurrency     string             `json:"risk_budget_currency"`
	RiskBudgetMeasure      string             `json:"risk_budget_measure"`
	RiskBudgetHorizon      string             `json:"risk_budget_horizon"`
	IntendedAction         string             `json:"intended_action"`
	Tags                   []string           `json:"tags"`
	Status                 string             `json:"status"`
	Author                 string             `json:"author"`
	SourceMetadata         []byte             `json:"source_metadata"`
	CreationSnapshot       []byte             `json:"creation_snapshot"`
	TimelineSequence       int64              `json:"timeline_sequence"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	FinalizedAt            pgtype.Timestamptz `json:"finalized_at"`
}

type DecisionAmendment struct {
	ID               pgtype.UUID        `json:"id"`
	DecisionID       pgtype.UUID        `json:"decision_id"`
	Summary          string             `json:"summary"`
	Changes          []byte             `json:"changes"`
	Author           string             `json:"author"`
	SourceMetadata   []byte             `json:"source_metadata"`
	TimelineSequence int64              `json:"timeline_sequence"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type DecisionEvidence struct {
	DecisionID     pgtype.UUID        `json:"decision_id"`
	ManifestBytes  []byte             `json:"manifest_bytes"`
	ManifestSha256 string             `json:"manifest_sha256"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DecisionReview struct {
	ID               pgtype.UUID        `json:"id"`
	DecisionID       pgtype.UUID        `json:"decision_id"`
	Review           string             `json:"review"`
	Outcome          string             `json:"outcome"`
	Author           string             `json:"author"`
	SourceMetadata   []byte             `json:"source_metadata"`
	TimelineSequence int64              `json:"timeline_sequence"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type FxQuoteRevision struct {
	ID                 pgtype.UUID        `json:"id"`
	BaseCurrency       string             `json:"base_currency"`
	QuoteCurrency      string             `json:"quote_currency"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Rate               pgtype.Numeric     `json:"rate"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

type ImportPreviewToken struct {
	TokenDigest          string             `json:"token_digest"`
	ImportKind           string             `json:"import_kind"`
	TargetID             pgtype.UUID        `json:"target_id"`
	CapturedAt           pgtype.Timestamptz `json:"captured_at"`
	SchemaVersion        string             `json:"schema_version"`
	ContentSha256        string             `json:"content_sha256"`
	RowCount             int32              `json:"row_count"`
	Diagnostics          []byte             `json:"diagnostics"`
	DiagnosticsTruncated bool               `json:"diagnostics_truncated"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt           pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type ImportResult struct {
	ID             pgtype.UUID        `json:"id"`
	ImportKind     string             `json:"import_kind"`
	IdempotencyKey string             `json:"idempotency_key"`
	TargetID       pgtype.UUID        `json:"target_id"`
	CapturedAt     pgtype.Timestamptz `json:"captured_at"`
	SchemaVersion  string             `json:"schema_version"`
	ContentSha256  string             `json:"content_sha256"`
	RowCount       int32              `json:"row_count"`
	RawObjectID    pgtype.UUID        `json:"raw_object_id"`
	Response       []byte             `json:"response"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type IngestionRun struct {
	ID             pgtype.UUID        `json:"id"`
	SourceID       pgtype.UUID        `json:"source_id"`
	DatasetID      pgtype.UUID        `json:"dataset_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	AdapterVersion string             `json:"adapter_version"`
	RequestedFrom  pgtype.Timestamptz `json:"requested_from"`
	RequestedTo    pgtype.Timestamptz `json:"requested_to"`
	Status         string             `json:"status"`
	Coverage       []byte             `json:"coverage"`
	ErrorCode      *string            `json:"error_code"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type Instrument struct {
	ID              pgtype.UUID        `json:"id"`
	CanonicalSymbol string             `json:"canonical_symbol"`
	InstrumentType  string             `json:"instrument_type"`
	NativeCurrency  string             `json:"native_currency"`
	ExternalIds     []byte             `json:"external_ids"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type InstrumentExternalIdentifier struct {
	InstrumentID pgtype.UUID        `json:"instrument_id"`
	Namespace    string             `json:"namespace"`
	ExternalID   string             `json:"external_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type LatestFxQuoteRevision struct {
	ID                 pgtype.UUID        `json:"id"`
	BaseCurrency       string             `json:"base_currency"`
	QuoteCurrency      string             `json:"quote_currency"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Rate               pgtype.Numeric     `json:"rate"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

type LatestObservationRevision struct {
	ID                 pgtype.UUID        `json:"id"`
	SeriesID           pgtype.UUID        `json:"series_id"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Value              pgtype.Numeric     `json:"value"`
	ValueText          *string            `json:"value_text"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

type LatestPriceRevision struct {
	ID                 pgtype.UUID        `json:"id"`
	InstrumentID       pgtype.UUID        `json:"instrument_id"`
	QuoteCurrency      string             `json:"quote_currency"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Price              pgtype.Numeric     `json:"price"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

type ObservationRevision struct {
	ID                 pgtype.UUID        `json:"id"`
	SeriesID           pgtype.UUID        `json:"series_id"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Value              pgtype.Numeric     `json:"value"`
	ValueText          *string            `json:"value_text"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

type Portfolio struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	ReportingCurrency string             `json:"reporting_currency"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type PortfolioSnapshot struct {
	ID                   pgtype.UUID        `json:"id"`
	PortfolioID          pgtype.UUID        `json:"portfolio_id"`
	CapturedAt           pgtype.Timestamptz `json:"captured_at"`
	SupersedesSnapshotID pgtype.UUID        `json:"supersedes_snapshot_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type PortfolioSnapshotLine struct {
	ID                    pgtype.UUID        `json:"id"`
	PortfolioID           pgtype.UUID        `json:"portfolio_id"`
	SnapshotID            pgtype.UUID        `json:"snapshot_id"`
	AccountID             pgtype.UUID        `json:"account_id"`
	InstrumentID          pgtype.UUID        `json:"instrument_id"`
	Quantity              pgtype.Numeric     `json:"quantity"`
	TotalCostBasis        pgtype.Numeric     `json:"total_cost_basis"`
	ModifiedDurationYears pgtype.Numeric     `json:"modified_duration_years"`
	ConvexityYearsSquared pgtype.Numeric     `json:"convexity_years_squared"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type PriceRevision struct {
	ID                 pgtype.UUID        `json:"id"`
	InstrumentID       pgtype.UUID        `json:"instrument_id"`
	QuoteCurrency      string             `json:"quote_currency"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Price              pgtype.Numeric     `json:"price"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
}

type RawObject struct {
	ID              pgtype.UUID        `json:"id"`
	ContentSha256   string             `json:"content_sha256"`
	ObjectKey       string             `json:"object_key"`
	MediaType       string             `json:"media_type"`
	ByteLength      int64              `json:"byte_length"`
	RetrievedAt     pgtype.Timestamptz `json:"retrieved_at"`
	RequestUri      *string            `json:"request_uri"`
	RequestMetadata []byte             `json:"request_metadata"`
	IngestionRunID  pgtype.UUID        `json:"ingestion_run_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type RawObjectOccurrence struct {
	ID              pgtype.UUID        `json:"id"`
	RawObjectID     pgtype.UUID        `json:"raw_object_id"`
	IngestionRunID  pgtype.UUID        `json:"ingestion_run_id"`
	OccurrenceKey   string             `json:"occurrence_key"`
	RetrievedAt     pgtype.Timestamptz `json:"retrieved_at"`
	RequestUri      *string            `json:"request_uri"`
	RequestMetadata []byte             `json:"request_metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ReconciliationCheckpoint struct {
	ID                 pgtype.UUID        `json:"id"`
	ValuationID        pgtype.UUID        `json:"valuation_id"`
	AccountID          pgtype.UUID        `json:"account_id"`
	SourceLabel        string             `json:"source_label"`
	Currency           string             `json:"currency"`
	Cutoff             pgtype.Timestamptz `json:"cutoff"`
	ExternalNav        pgtype.Numeric     `json:"external_nav"`
	ValuationNav       pgtype.Numeric     `json:"valuation_nav"`
	AbsoluteDifference pgtype.Numeric     `json:"absolute_difference"`
	RelativeDifference pgtype.Numeric     `json:"relative_difference"`
	EffectiveTolerance pgtype.Numeric     `json:"effective_tolerance"`
	ToleranceVersion   int32              `json:"tolerance_version"`
	State              string             `json:"state"`
	ReasonCode         *string            `json:"reason_code"`
	LineCheckState     string             `json:"line_check_state"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ReconciliationLineCheck struct {
	ID                 pgtype.UUID        `json:"id"`
	ReconciliationID   pgtype.UUID        `json:"reconciliation_id"`
	SnapshotLineID     pgtype.UUID        `json:"snapshot_line_id"`
	ExternalAmount     pgtype.Numeric     `json:"external_amount"`
	ValuationAmount    pgtype.Numeric     `json:"valuation_amount"`
	Difference         pgtype.Numeric     `json:"difference"`
	AbsoluteDifference pgtype.Numeric     `json:"absolute_difference"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ReconciliationToleranceVersion struct {
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	Version         int32              `json:"version"`
	ToleranceAmount pgtype.Numeric     `json:"tolerance_amount"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type RiskJob struct {
	ID               pgtype.UUID        `json:"id"`
	Kind             string             `json:"kind"`
	SchemaVersion    string             `json:"schema_version"`
	IdempotencyKey   string             `json:"idempotency_key"`
	InputSnapshotIds []string           `json:"input_snapshot_ids"`
	Payload          []byte             `json:"payload"`
	State            string             `json:"state"`
	AttemptCount     int32              `json:"attempt_count"`
	MaxAttempts      int32              `json:"max_attempts"`
	AvailableAt      pgtype.Timestamptz `json:"available_at"`
	LeaseOwner       *string            `json:"lease_owner"`
	LeaseExpiresAt   pgtype.Timestamptz `json:"lease_expires_at"`
	Result           []byte             `json:"result"`
	ResultHash       *string            `json:"result_hash"`
	ErrorCode        *string            `json:"error_code"`
	ErrorMessage     *string            `json:"error_message"`
	ErrorDetails     []byte             `json:"error_details"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	InputHash        *string            `json:"input_hash"`
}

type RiskJobAttempt struct {
	ID             int64              `json:"id"`
	JobID          pgtype.UUID        `json:"job_id"`
	Attempt        int32              `json:"attempt"`
	WorkerID       string             `json:"worker_id"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	Outcome        *string            `json:"outcome"`
	ErrorCode      *string            `json:"error_code"`
	ErrorMessage   *string            `json:"error_message"`
	ErrorDetails   []byte             `json:"error_details"`
}

type Scenario struct {
	ID             pgtype.UUID        `json:"id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	Name           string             `json:"name"`
	TemplateKey    string             `json:"template_key"`
	CurrentVersion int32              `json:"current_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ScenarioRun struct {
	ID              pgtype.UUID        `json:"id"`
	ScenarioID      pgtype.UUID        `json:"scenario_id"`
	ScenarioVersion int32              `json:"scenario_version"`
	AccountID       pgtype.UUID        `json:"account_id"`
	SnapshotID      pgtype.UUID        `json:"snapshot_id"`
	JobID           pgtype.UUID        `json:"job_id"`
	State           string             `json:"state"`
	Result          []byte             `json:"result"`
	ResultHash      *string            `json:"result_hash"`
	RequestHash     string             `json:"request_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	ValuationID     pgtype.UUID        `json:"valuation_id"`
	InputProvenance []byte             `json:"input_provenance"`
}

type ScenarioRunFactorAttribution struct {
	RunID               pgtype.UUID        `json:"run_id"`
	Factor              string             `json:"factor"`
	Contribution        pgtype.Numeric     `json:"contribution"`
	Method              string             `json:"method"`
	MethodVersion       string             `json:"method_version"`
	InteractionResidual pgtype.Numeric     `json:"interaction_residual"`
	Tolerance           pgtype.Numeric     `json:"tolerance"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ScenarioRunMetric struct {
	RunID      pgtype.UUID        `json:"run_id"`
	MetricKey  string             `json:"metric_key"`
	PreValue   pgtype.Numeric     `json:"pre_value"`
	PostValue  pgtype.Numeric     `json:"post_value"`
	State      string             `json:"state"`
	ReasonCode *string            `json:"reason_code"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ScenarioRunPosition struct {
	RunID           pgtype.UUID        `json:"run_id"`
	SnapshotLineID  pgtype.UUID        `json:"snapshot_line_id"`
	InstrumentID    pgtype.UUID        `json:"instrument_id"`
	State           string             `json:"state"`
	ReasonCodes     []string           `json:"reason_codes"`
	PreValueTry     pgtype.Numeric     `json:"pre_value_try"`
	PostValueTry    pgtype.Numeric     `json:"post_value_try"`
	PnlTry          pgtype.Numeric     `json:"pnl_try"`
	PreValueUsd     pgtype.Numeric     `json:"pre_value_usd"`
	PostValueUsd    pgtype.Numeric     `json:"post_value_usd"`
	PnlUsd          pgtype.Numeric     `json:"pnl_usd"`
	PriceReturn     pgtype.Numeric     `json:"price_return"`
	YieldReturn     pgtype.Numeric     `json:"yield_return"`
	FxMultiplierTry pgtype.Numeric     `json:"fx_multiplier_try"`
	FxMultiplierUsd pgtype.Numeric     `json:"fx_multiplier_usd"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ScenarioRunPositionAttribution struct {
	RunID               pgtype.UUID        `json:"run_id"`
	SnapshotLineID      pgtype.UUID        `json:"snapshot_line_id"`
	InstrumentID        pgtype.UUID        `json:"instrument_id"`
	State               string             `json:"state"`
	TotalPnl            pgtype.Numeric     `json:"total_pnl"`
	FactorContributions []byte             `json:"factor_contributions"`
	Residual            pgtype.Numeric     `json:"residual"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ScenarioVersion struct {
	ScenarioID  pgtype.UUID        `json:"scenario_id"`
	Version     int32              `json:"version"`
	TemplateKey string             `json:"template_key"`
	Units       []byte             `json:"units"`
	Shocks      []byte             `json:"shocks"`
	Mappings    []byte             `json:"mappings"`
	Assumptions []byte             `json:"assumptions"`
	ContentHash string             `json:"content_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Series struct {
	ID                 pgtype.UUID        `json:"id"`
	DatasetID          pgtype.UUID        `json:"dataset_id"`
	SourceCode         string             `json:"source_code"`
	Name               string             `json:"name"`
	Unit               string             `json:"unit"`
	Frequency          string             `json:"frequency"`
	SeasonalAdjustment *string            `json:"seasonal_adjustment"`
	SourceTimezone     *string            `json:"source_timezone"`
	FreshnessPolicy    []byte             `json:"freshness_policy"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ValuationLine struct {
	ID                    pgtype.UUID        `json:"id"`
	RunID                 pgtype.UUID        `json:"run_id"`
	SnapshotLineID        pgtype.UUID        `json:"snapshot_line_id"`
	NativeCurrency        string             `json:"native_currency"`
	NativeAmount          pgtype.Numeric     `json:"native_amount"`
	TryAmount             pgtype.Numeric     `json:"try_amount"`
	UsdAmount             pgtype.Numeric     `json:"usd_amount"`
	State                 string             `json:"state"`
	ReasonCodes           []byte             `json:"reason_codes"`
	PriceMethod           string             `json:"price_method"`
	PriceRevisionID       pgtype.UUID        `json:"price_revision_id"`
	PriceQuoteUnit        *string            `json:"price_quote_unit"`
	TryFxQuoteRevisionIds []pgtype.UUID      `json:"try_fx_quote_revision_ids"`
	TryFxDirections       []string           `json:"try_fx_directions"`
	UsdFxQuoteRevisionIds []pgtype.UUID      `json:"usd_fx_quote_revision_ids"`
	UsdFxDirections       []string           `json:"usd_fx_directions"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type ValuationRun struct {
	ID                 pgtype.UUID        `json:"id"`
	SnapshotID         pgtype.UUID        `json:"snapshot_id"`
	Cutoff             pgtype.Timestamptz `json:"cutoff"`
	KnowledgeMode      string             `json:"knowledge_mode"`
	KnownAt            pgtype.Timestamptz `json:"known_at"`
	PriceMaxAgeSeconds int64              `json:"price_max_age_seconds"`
	FxMaxAgeSeconds    int64              `json:"fx_max_age_seconds"`
	Request            []byte             `json:"request"`
	State              string             `json:"state"`
	ResultHash         string             `json:"result_hash"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
