// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portfolio.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (portfolio_id, name, metadata)
VALUES ($1, $2, $3)
RETURNING id, portfolio_id, name, metadata, created_at, updated_at
`

type CreateAccountParams struct {
	PortfolioID pgtype.UUID `json:"portfolio_id"`
	Name        string      `json:"name"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.PortfolioID, arg.Name, arg.Metadata)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPortfolio = `-- name: CreatePortfolio :one
INSERT INTO portfolios (name, reporting_currency, metadata)
VALUES ($1, $2, $3)
RETURNING id, name, reporting_currency, metadata, created_at, updated_at
`

type CreatePortfolioParams struct {
	Name              string `json:"name"`
	ReportingCurrency string `json:"reporting_currency"`
	Metadata          []byte `json:"metadata"`
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error) {
	row := q.db.QueryRow(ctx, createPortfolio, arg.Name, arg.ReportingCurrency, arg.Metadata)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ReportingCurrency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPortfolioInstrument = `-- name: CreatePortfolioInstrument :one
INSERT INTO instruments (canonical_symbol, instrument_type, native_currency, external_ids, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, canonical_symbol, instrument_type, native_currency, external_ids, status, created_at
`

type CreatePortfolioInstrumentParams struct {
	CanonicalSymbol string `json:"canonical_symbol"`
	InstrumentType  string `json:"instrument_type"`
	NativeCurrency  string `json:"native_currency"`
	ExternalIds     []byte `json:"external_ids"`
	Status          string `json:"status"`
}

func (q *Queries) CreatePortfolioInstrument(ctx context.Context, arg CreatePortfolioInstrumentParams) (Instrument, error) {
	row := q.db.QueryRow(ctx, createPortfolioInstrument,
		arg.CanonicalSymbol,
		arg.InstrumentType,
		arg.NativeCurrency,
		arg.ExternalIds,
		arg.Status,
	)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.CanonicalSymbol,
		&i.InstrumentType,
		&i.NativeCurrency,
		&i.ExternalIds,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createPortfolioSnapshot = `-- name: CreatePortfolioSnapshot :one
INSERT INTO portfolio_snapshots (portfolio_id, captured_at, supersedes_snapshot_id)
VALUES ($1, $2, $3)
RETURNING id, portfolio_id, captured_at, supersedes_snapshot_id, created_at
`

type CreatePortfolioSnapshotParams struct {
	PortfolioID          pgtype.UUID        `json:"portfolio_id"`
	CapturedAt           pgtype.Timestamptz `json:"captured_at"`
	SupersedesSnapshotID pgtype.UUID        `json:"supersedes_snapshot_id"`
}

func (q *Queries) CreatePortfolioSnapshot(ctx context.Context, arg CreatePortfolioSnapshotParams) (PortfolioSnapshot, error) {
	row := q.db.QueryRow(ctx, createPortfolioSnapshot, arg.PortfolioID, arg.CapturedAt, arg.SupersedesSnapshotID)
	var i PortfolioSnapshot
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.CapturedAt,
		&i.SupersedesSnapshotID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePortfolio = `-- name: DeletePortfolio :execrows
DELETE FROM portfolios WHERE id = $1
`

func (q *Queries) DeletePortfolio(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePortfolio, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT id, portfolio_id, name, metadata, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPortfolio = `-- name: GetPortfolio :one
SELECT id, name, reporting_currency, metadata, created_at, updated_at FROM portfolios WHERE id = $1
`

func (q *Queries) GetPortfolio(ctx context.Context, id pgtype.UUID) (Portfolio, error) {
	row := q.db.QueryRow(ctx, getPortfolio, id)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ReportingCurrency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPortfolioInstrument = `-- name: GetPortfolioInstrument :one
SELECT id, canonical_symbol, instrument_type, native_currency, external_ids, status, created_at FROM instruments WHERE id = $1
`

func (q *Queries) GetPortfolioInstrument(ctx context.Context, id pgtype.UUID) (Instrument, error) {
	row := q.db.QueryRow(ctx, getPortfolioInstrument, id)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.CanonicalSymbol,
		&i.InstrumentType,
		&i.NativeCurrency,
		&i.ExternalIds,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPortfolioSnapshot = `-- name: GetPortfolioSnapshot :one
SELECT id, portfolio_id, captured_at, supersedes_snapshot_id, created_at FROM portfolio_snapshots WHERE id = $1
`

func (q *Queries) GetPortfolioSnapshot(ctx context.Context, id pgtype.UUID) (PortfolioSnapshot, error) {
	row := q.db.QueryRow(ctx, getPortfolioSnapshot, id)
	var i PortfolioSnapshot
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.CapturedAt,
		&i.SupersedesSnapshotID,
		&i.CreatedAt,
	)
	return i, err
}

const getPortfolioSnapshotLineCount = `-- name: GetPortfolioSnapshotLineCount :one
SELECT count(*)::bigint
FROM portfolio_snapshot_lines
WHERE snapshot_id = $1
`

func (q *Queries) GetPortfolioSnapshotLineCount(ctx context.Context, snapshotID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPortfolioSnapshotLineCount, snapshotID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertInstrumentExternalIdentifier = `-- name: InsertInstrumentExternalIdentifier :execrows
INSERT INTO instrument_external_identifiers (instrument_id, namespace, external_id)
VALUES ($1, $2, $3)
ON CONFLICT (instrument_id, namespace) DO NOTHING
`

type InsertInstrumentExternalIdentifierParams struct {
	InstrumentID pgtype.UUID `json:"instrument_id"`
	Namespace    string      `json:"namespace"`
	ExternalID   string      `json:"external_id"`
}

func (q *Queries) InsertInstrumentExternalIdentifier(ctx context.Context, arg InsertInstrumentExternalIdentifierParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInstrumentExternalIdentifier, arg.InstrumentID, arg.Namespace, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPortfolioSnapshotLine = `-- name: InsertPortfolioSnapshotLine :one
INSERT INTO portfolio_snapshot_lines (
    portfolio_id, snapshot_id, account_id, instrument_id, quantity,
    total_cost_basis, modified_duration_years, convexity_years_squared
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, portfolio_id, snapshot_id, account_id, instrument_id, quantity, total_cost_basis, modified_duration_years, convexity_years_squared, created_at
`

type InsertPortfolioSnapshotLineParams struct {
	PortfolioID           pgtype.UUID    `json:"portfolio_id"`
	SnapshotID            pgtype.UUID    `json:"snapshot_id"`
	AccountID             pgtype.UUID    `json:"account_id"`
	InstrumentID          pgtype.UUID    `json:"instrument_id"`
	Quantity              pgtype.Numeric `json:"quantity"`
	TotalCostBasis        pgtype.Numeric `json:"total_cost_basis"`
	ModifiedDurationYears pgtype.Numeric `json:"modified_duration_years"`
	ConvexityYearsSquared pgtype.Numeric `json:"convexity_years_squared"`
}

func (q *Queries) InsertPortfolioSnapshotLine(ctx context.Context, arg InsertPortfolioSnapshotLineParams) (PortfolioSnapshotLine, error) {
	row := q.db.QueryRow(ctx, insertPortfolioSnapshotLine,
		arg.PortfolioID,
		arg.SnapshotID,
		arg.AccountID,
		arg.InstrumentID,
		arg.Quantity,
		arg.TotalCostBasis,
		arg.ModifiedDurationYears,
		arg.ConvexityYearsSquared,
	)
	var i PortfolioSnapshotLine
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.SnapshotID,
		&i.AccountID,
		&i.InstrumentID,
		&i.Quantity,
		&i.TotalCostBasis,
		&i.ModifiedDurationYears,
		&i.ConvexityYearsSquared,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, portfolio_id, name, metadata, created_at, updated_at FROM accounts WHERE portfolio_id = $1 ORDER BY name, id
`

func (q *Queries) ListAccounts(ctx context.Context, portfolioID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstrumentExternalIdentifiers = `-- name: ListInstrumentExternalIdentifiers :many
SELECT namespace, external_id
FROM instrument_external_identifiers
WHERE instrument_id = $1
ORDER BY namespace, external_id
`

type ListInstrumentExternalIdentifiersRow struct {
	Namespace  string `json:"namespace"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) ListInstrumentExternalIdentifiers(ctx context.Context, instrumentID pgtype.UUID) ([]ListInstrumentExternalIdentifiersRow, error) {
	rows, err := q.db.Query(ctx, listInstrumentExternalIdentifiers, instrumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstrumentExternalIdentifiersRow{}
	for rows.Next() {
		var i ListInstrumentExternalIdentifiersRow
		if err := rows.Scan(&i.Namespace, &i.ExternalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortfolioInstruments = `-- name: ListPortfolioInstruments :many
SELECT id, canonical_symbol, instrument_type, native_currency, external_ids, status, created_at FROM instruments
ORDER BY canonical_symbol, id
`

func (q *Queries) ListPortfolioInstruments(ctx context.Context) ([]Instrument, error) {
	rows, err := q.db.Query(ctx, listPortfolioInstruments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Instrument{}
	for rows.Next() {
		var i Instrument
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalSymbol,
			&i.InstrumentType,
			&i.NativeCurrency,
			&i.ExternalIds,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortfolioSnapshotLines = `-- name: ListPortfolioSnapshotLines :many
SELECT
    l.id, l.portfolio_id, l.snapshot_id, l.account_id, l.instrument_id,
    l.quantity, l.total_cost_basis, l.modified_duration_years,
    l.convexity_years_squared, l.created_at,
    a.name AS account_name,
    i.canonical_symbol, i.instrument_type, i.native_currency, i.status
FROM portfolio_snapshot_lines AS l
JOIN accounts AS a ON a.id = l.account_id
JOIN instruments AS i ON i.id = l.instrument_id
WHERE l.snapshot_id = $1
ORDER BY a.name, i.canonical_symbol, l.id
`

type ListPortfolioSnapshotLinesRow struct {
	ID                    pgtype.UUID        `json:"id"`
	PortfolioID           pgtype.UUID        `json:"portfolio_id"`
	SnapshotID            pgtype.UUID        `json:"snapshot_id"`
	AccountID             pgtype.UUID        `json:"account_id"`
	InstrumentID          pgtype.UUID        `json:"instrument_id"`
	Quantity              pgtype.Numeric     `json:"quantity"`
	TotalCostBasis        pgtype.Numeric     `json:"total_cost_basis"`
	ModifiedDurationYears pgtype.Numeric     `json:"modified_duration_years"`
	ConvexityYearsSquared pgtype.Numeric     `json:"convexity_years_squared"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	AccountName           string             `json:"account_name"`
	CanonicalSymbol       string             `json:"canonical_symbol"`
	InstrumentType        string             `json:"instrument_type"`
	NativeCurrency        string             `json:"native_currency"`
	Status                string             `json:"status"`
}

func (q *Queries) ListPortfolioSnapshotLines(ctx context.Context, snapshotID pgtype.UUID) ([]ListPortfolioSnapshotLinesRow, error) {
	rows, err := q.db.Query(ctx, listPortfolioSnapshotLines, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPortfolioSnapshotLinesRow{}
	for rows.Next() {
		var i ListPortfolioSnapshotLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.SnapshotID,
			&i.AccountID,
			&i.InstrumentID,
			&i.Quantity,
			&i.TotalCostBasis,
			&i.ModifiedDurationYears,
			&i.ConvexityYearsSquared,
			&i.CreatedAt,
			&i.AccountName,
			&i.CanonicalSymbol,
			&i.InstrumentType,
			&i.NativeCurrency,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortfolioSnapshots = `-- name: ListPortfolioSnapshots :many
SELECT id, portfolio_id, captured_at, supersedes_snapshot_id, created_at FROM portfolio_snapshots
WHERE portfolio_id = $1
ORDER BY captured_at DESC, id DESC
`

func (q *Queries) ListPortfolioSnapshots(ctx context.Context, portfolioID pgtype.UUID) ([]PortfolioSnapshot, error) {
	rows, err := q.db.Query(ctx, listPortfolioSnapshots, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortfolioSnapshot{}
	for rows.Next() {
		var i PortfolioSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.CapturedAt,
			&i.SupersedesSnapshotID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortfolios = `-- name: ListPortfolios :many
SELECT id, name, reporting_currency, metadata, created_at, updated_at FROM portfolios ORDER BY name, id
`

func (q *Queries) ListPortfolios(ctx context.Context) ([]Portfolio, error) {
	rows, err := q.db.Query(ctx, listPortfolios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Portfolio{}
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ReportingCurrency,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $2, metadata = $3, updated_at = clock_timestamp()
WHERE id = $1
RETURNING id, portfolio_id, name, metadata, created_at, updated_at
`

type UpdateAccountParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount, arg.ID, arg.Name, arg.Metadata)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePortfolio = `-- name: UpdatePortfolio :one
UPDATE portfolios
SET name = $2, reporting_currency = $3, metadata = $4, updated_at = clock_timestamp()
WHERE id = $1
RETURNING id, name, reporting_currency, metadata, created_at, updated_at
`

type UpdatePortfolioParams struct {
	ID                pgtype.UUID `json:"id"`
	Name              string      `json:"name"`
	ReportingCurrency string      `json:"reporting_currency"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) (Portfolio, error) {
	row := q.db.QueryRow(ctx, updatePortfolio,
		arg.ID,
		arg.Name,
		arg.ReportingCurrency,
		arg.Metadata,
	)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ReportingCurrency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePortfolioInstrumentStatus = `-- name: UpdatePortfolioInstrumentStatus :one
UPDATE instruments
SET status = $2
WHERE id = $1
RETURNING id, canonical_symbol, instrument_type, native_currency, external_ids, status, created_at
`

type UpdatePortfolioInstrumentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdatePortfolioInstrumentStatus(ctx context.Context, arg UpdatePortfolioInstrumentStatusParams) (Instrument, error) {
	row := q.db.QueryRow(ctx, updatePortfolioInstrumentStatus, arg.ID, arg.Status)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.CanonicalSymbol,
		&i.InstrumentType,
		&i.NativeCurrency,
		&i.ExternalIds,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
