// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quality.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listQualityObservations = `-- name: ListQualityObservations :many
WITH latest AS (
    SELECT DISTINCT ON (series_id, observation_time)
           id, series_id, observation_time, value, value_text,
           system_known_at, quality_flags
    FROM observation_revisions
    WHERE series_id = $2::uuid
      AND observation_time >= $3::timestamptz
      AND observation_time < $4::timestamptz
      AND observation_time <= $1::timestamptz
      AND system_known_at <= $1::timestamptz
    ORDER BY series_id, observation_time, system_known_at DESC, id DESC
)
SELECT latest.id, latest.series_id, latest.observation_time,
       latest.system_known_at, latest.quality_flags,
       EXISTS (
           SELECT 1
           FROM observation_revisions AS prior
           WHERE prior.series_id = latest.series_id
             AND prior.observation_time = latest.observation_time
             AND prior.system_known_at <= $1::timestamptz
             AND (prior.value IS DISTINCT FROM latest.value
                  OR prior.value_text IS DISTINCT FROM latest.value_text)
       ) AS revised
FROM latest
ORDER BY latest.observation_time, latest.id
LIMIT 10001
`

type ListQualityObservationsParams struct {
	EvaluationCutoff pgtype.Timestamptz `json:"evaluation_cutoff"`
	SeriesID         pgtype.UUID        `json:"series_id"`
	FromTime         pgtype.Timestamptz `json:"from_time"`
	ToTime           pgtype.Timestamptz `json:"to_time"`
}

type ListQualityObservationsRow struct {
	ID              pgtype.UUID        `json:"id"`
	SeriesID        pgtype.UUID        `json:"series_id"`
	ObservationTime pgtype.Timestamptz `json:"observation_time"`
	SystemKnownAt   pgtype.Timestamptz `json:"system_known_at"`
	QualityFlags    []byte             `json:"quality_flags"`
	Revised         bool               `json:"revised"`
}

func (q *Queries) ListQualityObservations(ctx context.Context, arg ListQualityObservationsParams) ([]ListQualityObservationsRow, error) {
	rows, err := q.db.Query(ctx, listQualityObservations,
		arg.EvaluationCutoff,
		arg.SeriesID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQualityObservationsRow{}
	for rows.Next() {
		var i ListQualityObservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ObservationTime,
			&i.SystemKnownAt,
			&i.QualityFlags,
			&i.Revised,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
