// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetDataSourceByCode(ctx context.Context, code string) (DataSource, error)
	GetDataset(ctx context.Context, id pgtype.UUID) (Dataset, error)
	GetDatasetByExternalKey(ctx context.Context, arg GetDatasetByExternalKeyParams) (Dataset, error)
	GetFXQuoteRevision(ctx context.Context, id pgtype.UUID) (FxQuoteRevision, error)
	GetInstrument(ctx context.Context, id pgtype.UUID) (Instrument, error)
	GetInstrumentBySymbol(ctx context.Context, canonicalSymbol string) (Instrument, error)
	GetObservationRevision(ctx context.Context, id pgtype.UUID) (ObservationRevision, error)
	GetPriceRevision(ctx context.Context, id pgtype.UUID) (PriceRevision, error)
	GetRawObjectBySHA256(ctx context.Context, contentSha256 string) (RawObject, error)
	GetSeries(ctx context.Context, id pgtype.UUID) (Series, error)
	GetSeriesBySourceCode(ctx context.Context, arg GetSeriesBySourceCodeParams) (Series, error)
	GetTimelineSeries(ctx context.Context, id pgtype.UUID) (GetTimelineSeriesRow, error)
	InsertDataSource(ctx context.Context, arg InsertDataSourceParams) (int64, error)
	InsertDataset(ctx context.Context, arg InsertDatasetParams) (int64, error)
	InsertFXQuoteRevision(ctx context.Context, arg InsertFXQuoteRevisionParams) (int64, error)
	InsertInstrument(ctx context.Context, arg InsertInstrumentParams) (int64, error)
	InsertObservationRevision(ctx context.Context, arg InsertObservationRevisionParams) (int64, error)
	InsertPriceRevision(ctx context.Context, arg InsertPriceRevisionParams) (int64, error)
	InsertRawObject(ctx context.Context, arg InsertRawObjectParams) (int64, error)
	InsertSeries(ctx context.Context, arg InsertSeriesParams) (int64, error)
	ListFXQuoteRevisions(ctx context.Context, arg ListFXQuoteRevisionsParams) ([]FxQuoteRevision, error)
	ListFXQuotesSourceAsOf(ctx context.Context, arg ListFXQuotesSourceAsOfParams) ([]FxQuoteRevision, error)
	ListFXQuotesSystemAsOf(ctx context.Context, arg ListFXQuotesSystemAsOfParams) ([]FxQuoteRevision, error)
	ListObservationRevisions(ctx context.Context, arg ListObservationRevisionsParams) ([]ObservationRevision, error)
	ListObservationsSourceAsOf(ctx context.Context, arg ListObservationsSourceAsOfParams) ([]ObservationRevision, error)
	ListObservationsSystemAsOf(ctx context.Context, arg ListObservationsSystemAsOfParams) ([]ObservationRevision, error)
	ListPriceRevisions(ctx context.Context, arg ListPriceRevisionsParams) ([]PriceRevision, error)
	ListPricesSourceAsOf(ctx context.Context, arg ListPricesSourceAsOfParams) ([]PriceRevision, error)
	ListPricesSystemAsOf(ctx context.Context, arg ListPricesSystemAsOfParams) ([]PriceRevision, error)
	ListSeriesByDataset(ctx context.Context, datasetID pgtype.UUID) ([]Series, error)
	ListTimelineObservationRevisions(ctx context.Context, arg ListTimelineObservationRevisionsParams) ([]ListTimelineObservationRevisionsRow, error)
	ListTimelineObservationsCombinedLatest(ctx context.Context, arg ListTimelineObservationsCombinedLatestParams) ([]ListTimelineObservationsCombinedLatestRow, error)
	ListTimelineObservationsCombinedSourceAsOf(ctx context.Context, arg ListTimelineObservationsCombinedSourceAsOfParams) ([]ListTimelineObservationsCombinedSourceAsOfRow, error)
	ListTimelineObservationsCombinedSystemAsOf(ctx context.Context, arg ListTimelineObservationsCombinedSystemAsOfParams) ([]ListTimelineObservationsCombinedSystemAsOfRow, error)
	ListTimelineObservationsLatest(ctx context.Context, arg ListTimelineObservationsLatestParams) ([]ListTimelineObservationsLatestRow, error)
	ListTimelineObservationsSourceAsOf(ctx context.Context, arg ListTimelineObservationsSourceAsOfParams) ([]ListTimelineObservationsSourceAsOfRow, error)
	ListTimelineObservationsSystemAsOf(ctx context.Context, arg ListTimelineObservationsSystemAsOfParams) ([]ListTimelineObservationsSystemAsOfRow, error)
	ListTimelineSeries(ctx context.Context, arg ListTimelineSeriesParams) ([]ListTimelineSeriesRow, error)
}

var _ Querier = (*Queries)(nil)
