// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timeline.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTimelineSeries = `-- name: GetTimelineSeries :one
SELECT s.id, s.dataset_id, s.source_code, s.name, s.unit, s.frequency,
       s.seasonal_adjustment, s.source_timezone, s.freshness_policy, s.created_at,
       ds.code AS data_source_code, ds.name AS data_source_name,
       d.external_key AS dataset_external_key,
       EXISTS (SELECT 1 FROM observation_revisions AS capability
               WHERE capability.series_id = s.id
                 AND capability.source_known_at IS NOT NULL) AS source_as_of_supported
FROM series AS s
JOIN datasets AS d ON d.id = s.dataset_id
JOIN data_sources AS ds ON ds.id = d.source_id
WHERE s.id = $1
`

type GetTimelineSeriesRow struct {
	ID                  pgtype.UUID        `json:"id"`
	DatasetID           pgtype.UUID        `json:"dataset_id"`
	SourceCode          string             `json:"source_code"`
	Name                string             `json:"name"`
	Unit                string             `json:"unit"`
	Frequency           string             `json:"frequency"`
	SeasonalAdjustment  *string            `json:"seasonal_adjustment"`
	SourceTimezone      *string            `json:"source_timezone"`
	FreshnessPolicy     []byte             `json:"freshness_policy"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	DataSourceCode      string             `json:"data_source_code"`
	DataSourceName      string             `json:"data_source_name"`
	DatasetExternalKey  string             `json:"dataset_external_key"`
	SourceAsOfSupported bool               `json:"source_as_of_supported"`
}

func (q *Queries) GetTimelineSeries(ctx context.Context, id pgtype.UUID) (GetTimelineSeriesRow, error) {
	row := q.db.QueryRow(ctx, getTimelineSeries, id)
	var i GetTimelineSeriesRow
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.SourceCode,
		&i.Name,
		&i.Unit,
		&i.Frequency,
		&i.SeasonalAdjustment,
		&i.SourceTimezone,
		&i.FreshnessPolicy,
		&i.CreatedAt,
		&i.DataSourceCode,
		&i.DataSourceName,
		&i.DatasetExternalKey,
		&i.SourceAsOfSupported,
	)
	return i, err
}

const listTimelineObservationRevisions = `-- name: ListTimelineObservationRevisions :many
SELECT o.id, o.series_id, o.observation_time, o.value, o.value_text,
       o.source_known_at, o.system_known_at, o.knowledge_time_basis,
       o.raw_object_id, o.quality_flags, ro.content_sha256 AS raw_object_sha256,
       s.unit, s.frequency, ds.code AS data_source_code
FROM observation_revisions AS o
JOIN series AS s ON s.id = o.series_id
JOIN datasets AS d ON d.id = s.dataset_id
JOIN data_sources AS ds ON ds.id = d.source_id
JOIN raw_objects AS ro ON ro.id = o.raw_object_id
WHERE o.series_id = $1 AND o.observation_time >= $2 AND o.observation_time < $3
  AND ($5::boolean = false OR (o.observation_time > $6 OR
       (o.observation_time = $6 AND o.system_known_at > $7) OR
       (o.observation_time = $6 AND o.system_known_at = $7 AND o.id > $8::uuid)))
ORDER BY o.observation_time, o.system_known_at, o.id
LIMIT $4
`

type ListTimelineObservationRevisionsParams struct {
	SeriesID          pgtype.UUID        `json:"series_id"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
	Limit             int32              `json:"limit"`
	Column5           bool               `json:"column_5"`
	ObservationTime_3 pgtype.Timestamptz `json:"observation_time_3"`
	SystemKnownAt     pgtype.Timestamptz `json:"system_known_at"`
	Column8           pgtype.UUID        `json:"column_8"`
}

type ListTimelineObservationRevisionsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SeriesID           pgtype.UUID        `json:"series_id"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Value              pgtype.Numeric     `json:"value"`
	ValueText          *string            `json:"value_text"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
	RawObjectSha256    string             `json:"raw_object_sha256"`
	Unit               string             `json:"unit"`
	Frequency          string             `json:"frequency"`
	DataSourceCode     string             `json:"data_source_code"`
}

func (q *Queries) ListTimelineObservationRevisions(ctx context.Context, arg ListTimelineObservationRevisionsParams) ([]ListTimelineObservationRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listTimelineObservationRevisions,
		arg.SeriesID,
		arg.ObservationTime,
		arg.ObservationTime_2,
		arg.Limit,
		arg.Column5,
		arg.ObservationTime_3,
		arg.SystemKnownAt,
		arg.Column8,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineObservationRevisionsRow{}
	for rows.Next() {
		var i ListTimelineObservationRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ObservationTime,
			&i.Value,
			&i.ValueText,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
			&i.RawObjectSha256,
			&i.Unit,
			&i.Frequency,
			&i.DataSourceCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineObservationsCombinedLatest = `-- name: ListTimelineObservationsCombinedLatest :many
SELECT o.id, o.series_id, o.observation_time, o.value, o.value_text,
       o.source_known_at, o.system_known_at, o.knowledge_time_basis,
       o.raw_object_id, o.quality_flags, ro.content_sha256 AS raw_object_sha256,
       s.unit, s.frequency, ds.code AS data_source_code
FROM latest_observation_revisions AS o
JOIN series AS s ON s.id = o.series_id
JOIN datasets AS d ON d.id = s.dataset_id
JOIN data_sources AS ds ON ds.id = d.source_id
JOIN raw_objects AS ro ON ro.id = o.raw_object_id
WHERE o.series_id = ANY($1::uuid[])
  AND o.observation_time >= $2 AND o.observation_time < $3
  AND ($5::boolean = false OR (o.observation_time > $6 OR
       (o.observation_time = $6 AND o.series_id > $7::uuid) OR
       (o.observation_time = $6 AND o.series_id = $7::uuid AND o.id > $8::uuid)))
ORDER BY o.observation_time, o.series_id, o.id
LIMIT $4
`

type ListTimelineObservationsCombinedLatestParams struct {
	Column1           []pgtype.UUID      `json:"column_1"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
	Limit             int32              `json:"limit"`
	Column5           bool               `json:"column_5"`
	ObservationTime_3 pgtype.Timestamptz `json:"observation_time_3"`
	Column7           pgtype.UUID        `json:"column_7"`
	Column8           pgtype.UUID        `json:"column_8"`
}

type ListTimelineObservationsCombinedLatestRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SeriesID           pgtype.UUID        `json:"series_id"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Value              pgtype.Numeric     `json:"value"`
	ValueText          *string            `json:"value_text"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
	RawObjectSha256    string             `json:"raw_object_sha256"`
	Unit               string             `json:"unit"`
	Frequency          string             `json:"frequency"`
	DataSourceCode     string             `json:"data_source_code"`
}

func (q *Queries) ListTimelineObservationsCombinedLatest(ctx context.Context, arg ListTimelineObservationsCombinedLatestParams) ([]ListTimelineObservationsCombinedLatestRow, error) {
	rows, err := q.db.Query(ctx, listTimelineObservationsCombinedLatest,
		arg.Column1,
		arg.ObservationTime,
		arg.ObservationTime_2,
		arg.Limit,
		arg.Column5,
		arg.ObservationTime_3,
		arg.Column7,
		arg.Column8,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineObservationsCombinedLatestRow{}
	for rows.Next() {
		var i ListTimelineObservationsCombinedLatestRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ObservationTime,
			&i.Value,
			&i.ValueText,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
			&i.RawObjectSha256,
			&i.Unit,
			&i.Frequency,
			&i.DataSourceCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineObservationsCombinedSourceAsOf = `-- name: ListTimelineObservationsCombinedSourceAsOf :many
WITH ranked AS (
  SELECT DISTINCT ON (series_id, observation_time) id, series_id, observation_time, value, value_text,
         source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags
  FROM observation_revisions
  WHERE series_id = ANY($1::uuid[])
    AND observation_time >= $2 AND observation_time < $3
    AND source_known_at IS NOT NULL AND source_known_at <= $4::timestamptz
  ORDER BY series_id, observation_time, source_known_at DESC, system_known_at DESC, id DESC
), filtered AS (
  SELECT id, series_id, observation_time, value, value_text, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM ranked
  WHERE ($6::boolean = false OR (observation_time > $7 OR
         (observation_time = $7 AND series_id > $8::uuid) OR
         (observation_time = $7 AND series_id = $8::uuid AND id > $9::uuid)))
)
SELECT filtered.id, filtered.series_id, filtered.observation_time, filtered.value, filtered.value_text,
       filtered.source_known_at, filtered.system_known_at, filtered.knowledge_time_basis,
       filtered.raw_object_id, filtered.quality_flags, ro.content_sha256 AS raw_object_sha256,
       s.unit, s.frequency, ds.code AS data_source_code
FROM filtered
JOIN series AS s ON s.id = filtered.series_id
JOIN datasets AS d ON d.id = s.dataset_id
JOIN data_sources AS ds ON ds.id = d.source_id
JOIN raw_objects AS ro ON ro.id = filtered.raw_object_id
ORDER BY filtered.observation_time, filtered.series_id, filtered.id
LIMIT $5
`

type ListTimelineObservationsCombinedSourceAsOfParams struct {
	Column1           []pgtype.UUID      `json:"column_1"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
	Column4           pgtype.Timestamptz `json:"column_4"`
	Limit             int32              `json:"limit"`
	Column6           bool               `json:"column_6"`
	ObservationTime_3 pgtype.Timestamptz `json:"observation_time_3"`
	Column8           pgtype.UUID        `json:"column_8"`
	Column9           pgtype.UUID        `json:"column_9"`
}

type ListTimelineObservationsCombinedSourceAsOfRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SeriesID           pgtype.UUID        `json:"series_id"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Value              pgtype.Numeric     `json:"value"`
	ValueText          *string            `json:"value_text"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
	RawObjectSha256    string             `json:"raw_object_sha256"`
	Unit               string             `json:"unit"`
	Frequency          string             `json:"frequency"`
	DataSourceCode     string             `json:"data_source_code"`
}

func (q *Queries) ListTimelineObservationsCombinedSourceAsOf(ctx context.Context, arg ListTimelineObservationsCombinedSourceAsOfParams) ([]ListTimelineObservationsCombinedSourceAsOfRow, error) {
	rows, err := q.db.Query(ctx, listTimelineObservationsCombinedSourceAsOf,
		arg.Column1,
		arg.ObservationTime,
		arg.ObservationTime_2,
		arg.Column4,
		arg.Limit,
		arg.Column6,
		arg.ObservationTime_3,
		arg.Column8,
		arg.Column9,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineObservationsCombinedSourceAsOfRow{}
	for rows.Next() {
		var i ListTimelineObservationsCombinedSourceAsOfRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ObservationTime,
			&i.Value,
			&i.ValueText,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
			&i.RawObjectSha256,
			&i.Unit,
			&i.Frequency,
			&i.DataSourceCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineObservationsCombinedSystemAsOf = `-- name: ListTimelineObservationsCombinedSystemAsOf :many
WITH ranked AS (
  SELECT DISTINCT ON (series_id, observation_time) id, series_id, observation_time, value, value_text,
         source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags
  FROM observation_revisions
  WHERE series_id = ANY($1::uuid[])
    AND observation_time >= $2 AND observation_time < $3
    AND system_known_at <= $4::timestamptz
  ORDER BY series_id, observation_time, system_known_at DESC, id DESC
), filtered AS (
  SELECT id, series_id, observation_time, value, value_text, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM ranked
  WHERE ($6::boolean = false OR (observation_time > $7 OR
         (observation_time = $7 AND series_id > $8::uuid) OR
         (observation_time = $7 AND series_id = $8::uuid AND id > $9::uuid)))
)
SELECT filtered.id, filtered.series_id, filtered.observation_time, filtered.value, filtered.value_text,
       filtered.source_known_at, filtered.system_known_at, filtered.knowledge_time_basis,
       filtered.raw_object_id, filtered.quality_flags, ro.content_sha256 AS raw_object_sha256,
       s.unit, s.frequency, ds.code AS data_source_code
FROM filtered
JOIN series AS s ON s.id = filtered.series_id
JOIN datasets AS d ON d.id = s.dataset_id
JOIN data_sources AS ds ON ds.id = d.source_id
JOIN raw_objects AS ro ON ro.id = filtered.raw_object_id
ORDER BY filtered.observation_time, filtered.series_id, filtered.id
LIMIT $5
`

type ListTimelineObservationsCombinedSystemAsOfParams struct {
	Column1           []pgtype.UUID      `json:"column_1"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
	Column4           pgtype.Timestamptz `json:"column_4"`
	Limit             int32              `json:"limit"`
	Column6           bool               `json:"column_6"`
	ObservationTime_3 pgtype.Timestamptz `json:"observation_time_3"`
	Column8           pgtype.UUID        `json:"column_8"`
	Column9           pgtype.UUID        `json:"column_9"`
}

type ListTimelineObservationsCombinedSystemAsOfRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SeriesID           pgtype.UUID        `json:"series_id"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Value              pgtype.Numeric     `json:"value"`
	ValueText          *string            `json:"value_text"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
	RawObjectSha256    string             `json:"raw_object_sha256"`
	Unit               string             `json:"unit"`
	Frequency          string             `json:"frequency"`
	DataSourceCode     string             `json:"data_source_code"`
}

func (q *Queries) ListTimelineObservationsCombinedSystemAsOf(ctx context.Context, arg ListTimelineObservationsCombinedSystemAsOfParams) ([]ListTimelineObservationsCombinedSystemAsOfRow, error) {
	rows, err := q.db.Query(ctx, listTimelineObservationsCombinedSystemAsOf,
		arg.Column1,
		arg.ObservationTime,
		arg.ObservationTime_2,
		arg.Column4,
		arg.Limit,
		arg.Column6,
		arg.ObservationTime_3,
		arg.Column8,
		arg.Column9,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineObservationsCombinedSystemAsOfRow{}
	for rows.Next() {
		var i ListTimelineObservationsCombinedSystemAsOfRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ObservationTime,
			&i.Value,
			&i.ValueText,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
			&i.RawObjectSha256,
			&i.Unit,
			&i.Frequency,
			&i.DataSourceCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineObservationsLatest = `-- name: ListTimelineObservationsLatest :many
SELECT o.id, o.series_id, o.observation_time, o.value, o.value_text,
       o.source_known_at, o.system_known_at, o.knowledge_time_basis,
       o.raw_object_id, o.quality_flags, ro.content_sha256 AS raw_object_sha256,
       s.unit, s.frequency, ds.code AS data_source_code
FROM latest_observation_revisions AS o
JOIN series AS s ON s.id = o.series_id
JOIN datasets AS d ON d.id = s.dataset_id
JOIN data_sources AS ds ON ds.id = d.source_id
JOIN raw_objects AS ro ON ro.id = o.raw_object_id
WHERE o.series_id = $1 AND o.observation_time >= $2 AND o.observation_time < $3
  AND ($5::boolean = false OR (o.observation_time > $6 OR (o.observation_time = $6 AND o.id > $7::uuid)))
ORDER BY o.observation_time, o.id
LIMIT $4
`

type ListTimelineObservationsLatestParams struct {
	SeriesID          pgtype.UUID        `json:"series_id"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
	Limit             int32              `json:"limit"`
	Column5           bool               `json:"column_5"`
	ObservationTime_3 pgtype.Timestamptz `json:"observation_time_3"`
	Column7           pgtype.UUID        `json:"column_7"`
}

type ListTimelineObservationsLatestRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SeriesID           pgtype.UUID        `json:"series_id"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Value              pgtype.Numeric     `json:"value"`
	ValueText          *string            `json:"value_text"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
	RawObjectSha256    string             `json:"raw_object_sha256"`
	Unit               string             `json:"unit"`
	Frequency          string             `json:"frequency"`
	DataSourceCode     string             `json:"data_source_code"`
}

func (q *Queries) ListTimelineObservationsLatest(ctx context.Context, arg ListTimelineObservationsLatestParams) ([]ListTimelineObservationsLatestRow, error) {
	rows, err := q.db.Query(ctx, listTimelineObservationsLatest,
		arg.SeriesID,
		arg.ObservationTime,
		arg.ObservationTime_2,
		arg.Limit,
		arg.Column5,
		arg.ObservationTime_3,
		arg.Column7,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineObservationsLatestRow{}
	for rows.Next() {
		var i ListTimelineObservationsLatestRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ObservationTime,
			&i.Value,
			&i.ValueText,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
			&i.RawObjectSha256,
			&i.Unit,
			&i.Frequency,
			&i.DataSourceCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineObservationsSourceAsOf = `-- name: ListTimelineObservationsSourceAsOf :many
WITH ranked AS (
  SELECT DISTINCT ON (series_id, observation_time) id, series_id, observation_time, value, value_text,
         source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags
  FROM observation_revisions
  WHERE series_id = $1 AND observation_time >= $2 AND observation_time < $3
    AND source_known_at IS NOT NULL AND source_known_at <= $4::timestamptz
  ORDER BY series_id, observation_time, source_known_at DESC, system_known_at DESC, id DESC
), filtered AS (
  SELECT id, series_id, observation_time, value, value_text, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM ranked
  WHERE ($6::boolean = false OR (observation_time > $7 OR (observation_time = $7 AND id > $8::uuid)))
)
SELECT filtered.id, filtered.series_id, filtered.observation_time, filtered.value, filtered.value_text,
       filtered.source_known_at, filtered.system_known_at, filtered.knowledge_time_basis,
       filtered.raw_object_id, filtered.quality_flags, ro.content_sha256 AS raw_object_sha256,
       s.unit, s.frequency, ds.code AS data_source_code
FROM filtered
JOIN series AS s ON s.id = filtered.series_id
JOIN datasets AS d ON d.id = s.dataset_id
JOIN data_sources AS ds ON ds.id = d.source_id
JOIN raw_objects AS ro ON ro.id = filtered.raw_object_id
ORDER BY filtered.observation_time, filtered.id
LIMIT $5
`

type ListTimelineObservationsSourceAsOfParams struct {
	SeriesID          pgtype.UUID        `json:"series_id"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
	Column4           pgtype.Timestamptz `json:"column_4"`
	Limit             int32              `json:"limit"`
	Column6           bool               `json:"column_6"`
	ObservationTime_3 pgtype.Timestamptz `json:"observation_time_3"`
	Column8           pgtype.UUID        `json:"column_8"`
}

type ListTimelineObservationsSourceAsOfRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SeriesID           pgtype.UUID        `json:"series_id"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Value              pgtype.Numeric     `json:"value"`
	ValueText          *string            `json:"value_text"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
	RawObjectSha256    string             `json:"raw_object_sha256"`
	Unit               string             `json:"unit"`
	Frequency          string             `json:"frequency"`
	DataSourceCode     string             `json:"data_source_code"`
}

func (q *Queries) ListTimelineObservationsSourceAsOf(ctx context.Context, arg ListTimelineObservationsSourceAsOfParams) ([]ListTimelineObservationsSourceAsOfRow, error) {
	rows, err := q.db.Query(ctx, listTimelineObservationsSourceAsOf,
		arg.SeriesID,
		arg.ObservationTime,
		arg.ObservationTime_2,
		arg.Column4,
		arg.Limit,
		arg.Column6,
		arg.ObservationTime_3,
		arg.Column8,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineObservationsSourceAsOfRow{}
	for rows.Next() {
		var i ListTimelineObservationsSourceAsOfRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ObservationTime,
			&i.Value,
			&i.ValueText,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
			&i.RawObjectSha256,
			&i.Unit,
			&i.Frequency,
			&i.DataSourceCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineObservationsSystemAsOf = `-- name: ListTimelineObservationsSystemAsOf :many
WITH ranked AS (
  SELECT DISTINCT ON (series_id, observation_time) id, series_id, observation_time, value, value_text,
         source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags
  FROM observation_revisions
  WHERE series_id = $1 AND observation_time >= $2 AND observation_time < $3
    AND system_known_at <= $4::timestamptz
  ORDER BY series_id, observation_time, system_known_at DESC, id DESC
), filtered AS (
  SELECT id, series_id, observation_time, value, value_text, source_known_at, system_known_at, knowledge_time_basis, raw_object_id, quality_flags FROM ranked
  WHERE ($6::boolean = false OR (observation_time > $7 OR (observation_time = $7 AND id > $8::uuid)))
)
SELECT filtered.id, filtered.series_id, filtered.observation_time, filtered.value, filtered.value_text,
       filtered.source_known_at, filtered.system_known_at, filtered.knowledge_time_basis,
       filtered.raw_object_id, filtered.quality_flags, ro.content_sha256 AS raw_object_sha256,
       s.unit, s.frequency, ds.code AS data_source_code
FROM filtered
JOIN series AS s ON s.id = filtered.series_id
JOIN datasets AS d ON d.id = s.dataset_id
JOIN data_sources AS ds ON ds.id = d.source_id
JOIN raw_objects AS ro ON ro.id = filtered.raw_object_id
ORDER BY filtered.observation_time, filtered.id
LIMIT $5
`

type ListTimelineObservationsSystemAsOfParams struct {
	SeriesID          pgtype.UUID        `json:"series_id"`
	ObservationTime   pgtype.Timestamptz `json:"observation_time"`
	ObservationTime_2 pgtype.Timestamptz `json:"observation_time_2"`
	Column4           pgtype.Timestamptz `json:"column_4"`
	Limit             int32              `json:"limit"`
	Column6           bool               `json:"column_6"`
	ObservationTime_3 pgtype.Timestamptz `json:"observation_time_3"`
	Column8           pgtype.UUID        `json:"column_8"`
}

type ListTimelineObservationsSystemAsOfRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SeriesID           pgtype.UUID        `json:"series_id"`
	ObservationTime    pgtype.Timestamptz `json:"observation_time"`
	Value              pgtype.Numeric     `json:"value"`
	ValueText          *string            `json:"value_text"`
	SourceKnownAt      pgtype.Timestamptz `json:"source_known_at"`
	SystemKnownAt      pgtype.Timestamptz `json:"system_known_at"`
	KnowledgeTimeBasis string             `json:"knowledge_time_basis"`
	RawObjectID        pgtype.UUID        `json:"raw_object_id"`
	QualityFlags       []byte             `json:"quality_flags"`
	RawObjectSha256    string             `json:"raw_object_sha256"`
	Unit               string             `json:"unit"`
	Frequency          string             `json:"frequency"`
	DataSourceCode     string             `json:"data_source_code"`
}

func (q *Queries) ListTimelineObservationsSystemAsOf(ctx context.Context, arg ListTimelineObservationsSystemAsOfParams) ([]ListTimelineObservationsSystemAsOfRow, error) {
	rows, err := q.db.Query(ctx, listTimelineObservationsSystemAsOf,
		arg.SeriesID,
		arg.ObservationTime,
		arg.ObservationTime_2,
		arg.Column4,
		arg.Limit,
		arg.Column6,
		arg.ObservationTime_3,
		arg.Column8,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineObservationsSystemAsOfRow{}
	for rows.Next() {
		var i ListTimelineObservationsSystemAsOfRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ObservationTime,
			&i.Value,
			&i.ValueText,
			&i.SourceKnownAt,
			&i.SystemKnownAt,
			&i.KnowledgeTimeBasis,
			&i.RawObjectID,
			&i.QualityFlags,
			&i.RawObjectSha256,
			&i.Unit,
			&i.Frequency,
			&i.DataSourceCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineSeries = `-- name: ListTimelineSeries :many
SELECT s.id, s.dataset_id, s.source_code, s.name, s.unit, s.frequency,
       s.seasonal_adjustment, s.source_timezone, s.freshness_policy, s.created_at,
       ds.code AS data_source_code, ds.name AS data_source_name,
       d.external_key AS dataset_external_key,
       EXISTS (SELECT 1 FROM observation_revisions AS capability
               WHERE capability.series_id = s.id
                 AND capability.source_known_at IS NOT NULL) AS source_as_of_supported
FROM series AS s
JOIN datasets AS d ON d.id = s.dataset_id
JOIN data_sources AS ds ON ds.id = d.source_id
WHERE ($1::boolean = false OR
       (ds.code > $2 OR
        (ds.code = $2 AND s.source_code > $3) OR
        (ds.code = $2 AND s.source_code = $3 AND s.id > $4::uuid)))
ORDER BY ds.code, s.source_code, s.id
LIMIT $5
`

type ListTimelineSeriesParams struct {
	Column1    bool        `json:"column_1"`
	Code       string      `json:"code"`
	SourceCode string      `json:"source_code"`
	Column4    pgtype.UUID `json:"column_4"`
	Limit      int32       `json:"limit"`
}

type ListTimelineSeriesRow struct {
	ID                  pgtype.UUID        `json:"id"`
	DatasetID           pgtype.UUID        `json:"dataset_id"`
	SourceCode          string             `json:"source_code"`
	Name                string             `json:"name"`
	Unit                string             `json:"unit"`
	Frequency           string             `json:"frequency"`
	SeasonalAdjustment  *string            `json:"seasonal_adjustment"`
	SourceTimezone      *string            `json:"source_timezone"`
	FreshnessPolicy     []byte             `json:"freshness_policy"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	DataSourceCode      string             `json:"data_source_code"`
	DataSourceName      string             `json:"data_source_name"`
	DatasetExternalKey  string             `json:"dataset_external_key"`
	SourceAsOfSupported bool               `json:"source_as_of_supported"`
}

func (q *Queries) ListTimelineSeries(ctx context.Context, arg ListTimelineSeriesParams) ([]ListTimelineSeriesRow, error) {
	rows, err := q.db.Query(ctx, listTimelineSeries,
		arg.Column1,
		arg.Code,
		arg.SourceCode,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineSeriesRow{}
	for rows.Next() {
		var i ListTimelineSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.DatasetID,
			&i.SourceCode,
			&i.Name,
			&i.Unit,
			&i.Frequency,
			&i.SeasonalAdjustment,
			&i.SourceTimezone,
			&i.FreshnessPolicy,
			&i.CreatedAt,
			&i.DataSourceCode,
			&i.DataSourceName,
			&i.DatasetExternalKey,
			&i.SourceAsOfSupported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
